using System.Text;
using Newtonsoft.Json;

namespace FlowBlox.AIAssistant.Services
{
    internal sealed class AssistantOutputFormatFeedbackQueue
    {
        private readonly Queue<string> _messages = new();

        public string Enqueue(AssistantInstructionParseResult parseResult)
        {
            var message = BuildFeedbackMessage(parseResult);
            _messages.Enqueue(message);
            return message;
        }

        public string DequeuePromptOrEmpty()
        {
            return _messages.Count == 0
                ? string.Empty
                : _messages.Dequeue();
        }

        public void ClearIncorrectOutputFormatData()
        {
            _messages.Clear();
        }

        private static string BuildFeedbackMessage(AssistantInstructionParseResult parseResult)
        {
            var exception = parseResult?.Exception;
            var sb = new StringBuilder();
            sb.AppendLine("System note: The previous assistant response could not be accepted because FlowBlox failed to parse it as the required assistant JSON instruction.");
            sb.AppendLine("This note is generated by the FlowBlox system, not by the user.");
            sb.AppendLine();
            sb.AppendLine("Parsing failure:");
            sb.AppendLine(exception == null
                ? "No parser exception was captured."
                : exception.GetType().Name + ": " + exception.Message);

            if (exception is JsonReaderException jsonException)
            {
                sb.AppendLine($"JSON position: line {jsonException.LineNumber}, position {jsonException.LinePosition}");
                if (!string.IsNullOrWhiteSpace(jsonException.Path))
                    sb.AppendLine("JSON path: " + jsonException.Path);
            }

            sb.AppendLine();
            sb.AppendLine("Previous assistant response content:");
            sb.AppendLine(parseResult?.ResponseContent ?? string.Empty);
            sb.AppendLine();
            sb.AppendLine("For all future assistant responses, return exactly one valid JSON object and no text outside it.");
            sb.AppendLine("Required shape: {\"assistantMessage\":\"short status or final answer\",\"final\":false,\"toolCalls\":[{\"toolName\":\"ToolName\",\"arguments\":{}}]}");
            sb.AppendLine("Set \"final\" to true only when the complete user request is finished or provably blocked.");

            return sb.ToString().TrimEnd();
        }
    }
}