<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="UnitTest\Mockup\HTMLContent_Complex_Data_C1.html" />
    <None Remove="UnitTest\Mockup\HTMLContent_Complex_Data_C2.html" />
    <None Remove="UnitTest\Mockup\HTMLContent_Complex_MultipleMatches2_C1.html" />
    <None Remove="UnitTest\Mockup\HTMLContent_Complex_MultipleMatches2_C2.html" />
    <None Remove="UnitTest\Mockup\HTMLContent_Complex_MultipleMatches_C1.html" />
    <None Remove="UnitTest\Mockup\HTMLContent_Complex_MultipleMatches_C2.html" />
    <None Remove="UnitTest\Mockup\HTMLContent_MultipleMatches_Test_C1.html" />
    <None Remove="UnitTest\Mockup\HTMLContent_MultipleMatches_Test_C2.html" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="UnitTest\Mockup\HTMLContent_Complex_Data_C1.html" />
    <EmbeddedResource Include="UnitTest\Mockup\HTMLContent_Complex_Data_C2.html" />
    <EmbeddedResource Include="UnitTest\Mockup\HTMLContent_Complex_MultipleMatches_C1.html" />
    <EmbeddedResource Include="UnitTest\Mockup\HTMLContent_Complex_MultipleMatches_C2.html" />
    <EmbeddedResource Include="UnitTest\Mockup\HTMLContent_Complex_MultipleMatches2_C2.html" />
    <EmbeddedResource Include="UnitTest\Mockup\HTMLContent_MultipleMatches_Test_C2.html" />
    <EmbeddedResource Include="UnitTest\Mockup\HTMLContent_MultipleMatches_Test_C1.html" />
    <EmbeddedResource Include="UnitTest\Mockup\HTMLContent_Complex_MultipleMatches2_C1.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.2.3" />
    <PackageReference Include="MSTest.TestFramework" Version="4.2.3" />
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlowBlox.SequenceDetection\FlowBlox.SequenceDetection.csproj" />
  </ItemGroup>

</Project>
