//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowBlox.UICore.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AIAssistantControl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AIAssistantControl() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowBlox.UICore.Resources.AIAssistantControl", typeof(AIAssistantControl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Submit ähnelt.
        /// </summary>
        public static string Button_Submit {
            get {
                return ResourceManager.GetString("Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        public static string ContextMenu_Copy {
            get {
                return ResourceManager.GetString("ContextMenu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open in Editor ähnelt.
        /// </summary>
        public static string ContextMenu_OpenInEditor {
            get {
                return ResourceManager.GetString("ContextMenu_OpenInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The AI Assistant can help you adjust the current flow or create a complete flow from a description. ähnelt.
        /// </summary>
        public static string Header_Description {
            get {
                return ResourceManager.GetString("Header_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AI Assistant ähnelt.
        /// </summary>
        public static string Header_Title {
            get {
                return ResourceManager.GetString("Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The communication protocol directory does not exist: {0} ähnelt.
        /// </summary>
        public static string Message_CommunicationProtocolDirectory_NotFound_Description {
            get {
                return ResourceManager.GetString("Message_CommunicationProtocolDirectory_NotFound_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Communication Protocol Directory Not Found ähnelt.
        /// </summary>
        public static string Message_CommunicationProtocolDirectory_NotFound_Title {
            get {
                return ResourceManager.GetString("Message_CommunicationProtocolDirectory_NotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The communication protocol directory could not be opened. Details: {0} ähnelt.
        /// </summary>
        public static string Message_CommunicationProtocolDirectory_OpenFailed_Description {
            get {
                return ResourceManager.GetString("Message_CommunicationProtocolDirectory_OpenFailed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to Open Communication Protocol Directory ähnelt.
        /// </summary>
        public static string Message_CommunicationProtocolDirectory_OpenFailed_Title {
            get {
                return ResourceManager.GetString("Message_CommunicationProtocolDirectory_OpenFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to reset the assistant communication state? All session and transcript states will be reset. ähnelt.
        /// </summary>
        public static string Message_ResetCommunicationState_Question {
            get {
                return ResourceManager.GetString("Message_ResetCommunicationState_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset Communication State ähnelt.
        /// </summary>
        public static string Message_ResetCommunicationState_Title {
            get {
                return ResourceManager.GetString("Message_ResetCommunicationState_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configure AI Assistant ähnelt.
        /// </summary>
        public static string Tooltip_Configure {
            get {
                return ResourceManager.GetString("Tooltip_Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open communication protocol directory ähnelt.
        /// </summary>
        public static string Tooltip_OpenCommunicationProtocolDirectory {
            get {
                return ResourceManager.GetString("Tooltip_OpenCommunicationProtocolDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Redo last AI project state change ähnelt.
        /// </summary>
        public static string Tooltip_Redo {
            get {
                return ResourceManager.GetString("Tooltip_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset communication state ähnelt.
        /// </summary>
        public static string Tooltip_ResetCommunicationState {
            get {
                return ResourceManager.GetString("Tooltip_ResetCommunicationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undo last AI project state change ähnelt.
        /// </summary>
        public static string Tooltip_Undo {
            get {
                return ResourceManager.GetString("Tooltip_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please configure your AI provider first. API key required. ähnelt.
        /// </summary>
        public static string Warning_MissingProvider {
            get {
                return ResourceManager.GetString("Warning_MissingProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FlowBlox AI-Assistant ähnelt.
        /// </summary>
        public static string Watermark_Title {
            get {
                return ResourceManager.GetString("Watermark_Title", resourceCulture);
            }
        }
    }
}
