//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowBlox.UICore.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateOrUpdatePSProjectWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateOrUpdatePSProjectWindow() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowBlox.UICore.Resources.CreateOrUpdatePSProjectWindow", typeof(CreateOrUpdatePSProjectWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new project ähnelt.
        /// </summary>
        public static string Button_CreateNewProject {
            get {
                return ResourceManager.GetString("Button_CreateNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update existing project ähnelt.
        /// </summary>
        public static string Button_UpdateExistingProject {
            get {
                return ResourceManager.GetString("Button_UpdateExistingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are not logged in. Please log in first: Go to &quot;Extras&quot;, &quot;View projects&quot; and click &quot;Login&quot;. ähnelt.
        /// </summary>
        public static string CreateOrUpdatePSProjectWindow_Message_LoginRequired {
            get {
                return ResourceManager.GetString("CreateOrUpdatePSProjectWindow_Message_LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning: Found {0} ExecuteProject flow blocks that reference other project files via a file path (ProjectFile). When uploading into Project Space, these references may break.
        ///
        ///Please ensure that all referenced projects are available in Project Space as well, and migrate these references to Project Space GUIDs.
        ///
        ///Examples (max {1}):
        ///{2} ähnelt.
        /// </summary>
        public static string CreateOrUpdatePSProjectWindow_Warning_ExternalProjectReferences {
            get {
                return ResourceManager.GetString("CreateOrUpdatePSProjectWindow_Warning_ExternalProjectReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to create the project in Project Space. ähnelt.
        /// </summary>
        public static string Error_CreateFailed {
            get {
                return ResourceManager.GetString("Error_CreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You must be logged in to save to Project Space. ähnelt.
        /// </summary>
        public static string Error_NotLoggedIn {
            get {
                return ResourceManager.GetString("Error_NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The project metadata could not be refreshed after saving. ähnelt.
        /// </summary>
        public static string Error_RefreshMetadataFailed {
            get {
                return ResourceManager.GetString("Error_RefreshMetadataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to update project metadata. ähnelt.
        /// </summary>
        public static string Error_UpdateFailed {
            get {
                return ResourceManager.GetString("Error_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to upload project content. ähnelt.
        /// </summary>
        public static string Error_UploadFailed {
            get {
                return ResourceManager.GetString("Error_UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save the current project to your Project Space. If the project already exists, metadata and content will be updated. ähnelt.
        /// </summary>
        public static string Header_Description {
            get {
                return ResourceManager.GetString("Header_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save to Project Space ähnelt.
        /// </summary>
        public static string Header_Title {
            get {
                return ResourceManager.GetString("Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Created at ähnelt.
        /// </summary>
        public static string Label_CreatedAt {
            get {
                return ResourceManager.GetString("Label_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string Label_ProjectDescription {
            get {
                return ResourceManager.GetString("Label_ProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project GUID ähnelt.
        /// </summary>
        public static string Label_ProjectGuid {
            get {
                return ResourceManager.GetString("Label_ProjectGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project name ähnelt.
        /// </summary>
        public static string Label_ProjectName {
            get {
                return ResourceManager.GetString("Label_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last updated at ähnelt.
        /// </summary>
        public static string Label_UpdatedAt {
            get {
                return ResourceManager.GetString("Label_UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visibility ähnelt.
        /// </summary>
        public static string Label_Visibility {
            get {
                return ResourceManager.GetString("Label_Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project was saved successfully to Project Space. ähnelt.
        /// </summary>
        public static string Message_SaveSuccessful {
            get {
                return ResourceManager.GetString("Message_SaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Briefly describe the purpose and usage of this project… ähnelt.
        /// </summary>
        public static string Placeholder_ProjectDescription {
            get {
                return ResourceManager.GetString("Placeholder_ProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string Placeholder_ProjectGuid {
            get {
                return ResourceManager.GetString("Placeholder_ProjectGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die e.g. Contoso.Demo.Flow ähnelt.
        /// </summary>
        public static string Placeholder_ProjectName {
            get {
                return ResourceManager.GetString("Placeholder_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new project ähnelt.
        /// </summary>
        public static string Tab_CreateNewProject {
            get {
                return ResourceManager.GetString("Tab_CreateNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update existing project ähnelt.
        /// </summary>
        public static string Tab_UpdateExistingProject {
            get {
                return ResourceManager.GetString("Tab_UpdateExistingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save to Project Space ähnelt.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clears the current ProjectSpace GUID. On save, a new ProjectSpace project will be created with a new GUID. ähnelt.
        /// </summary>
        public static string Tooltip_CreateNewProject {
            get {
                return ResourceManager.GetString("Tooltip_CreateNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a new Project Space project and upload its content afterwards. ähnelt.
        /// </summary>
        public static string Tooltip_Tab_CreateNewProject {
            get {
                return ResourceManager.GetString("Tooltip_Tab_CreateNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update an existing Project Space project (requires a project GUID). ähnelt.
        /// </summary>
        public static string Tooltip_Tab_UpdateExistingProject {
            get {
                return ResourceManager.GetString("Tooltip_Tab_UpdateExistingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uses the existing ProjectSpace GUID and updates the current ProjectSpace project. ähnelt.
        /// </summary>
        public static string Tooltip_UpdateExistingProject {
            get {
                return ResourceManager.GetString("Tooltip_UpdateExistingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Private ähnelt.
        /// </summary>
        public static string Visibility_Private {
            get {
                return ResourceManager.GetString("Visibility_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Public ähnelt.
        /// </summary>
        public static string Visibility_Public {
            get {
                return ResourceManager.GetString("Visibility_Public", resourceCulture);
            }
        }
    }
}
