//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowBlox.UICore.Resources
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExecutionIndexWindow
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal ExecutionIndexWindow()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowBlox.UICore.Resources.ExecutionIndexWindow", typeof(ExecutionIndexWindow).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string Header_Title => ResourceManager.GetString("Header_Title", resourceCulture);
        public static string Header_Description => ResourceManager.GetString("Header_Description", resourceCulture);
        public static string Label_ExecutionIndex => ResourceManager.GetString("Label_ExecutionIndex", resourceCulture);
        public static string Button_Back => ResourceManager.GetString("Button_Back", resourceCulture);
        public static string Button_Remove => ResourceManager.GetString("Button_Remove", resourceCulture);
        public static string Button_Apply => ResourceManager.GetString("Button_Apply", resourceCulture);
        public static string Validation_InvalidIndex_Title => ResourceManager.GetString("Validation_InvalidIndex_Title", resourceCulture);
        public static string Validation_InvalidIndex_Message => ResourceManager.GetString("Validation_InvalidIndex_Message", resourceCulture);
    }
}
