//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowBlox.UICore.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExtensionsWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExtensionsWindow() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowBlox.UICore.Resources.ExtensionsWindow", typeof(ExtensionsWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log in ähnelt.
        /// </summary>
        public static string Button_Login {
            get {
                return ResourceManager.GetString("Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log out ähnelt.
        /// </summary>
        public static string Button_Logout {
            get {
                return ResourceManager.GetString("Button_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage own extensions ähnelt.
        /// </summary>
        public static string Button_ManageOwnExtensions {
            get {
                return ResourceManager.GetString("Button_ManageOwnExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register ähnelt.
        /// </summary>
        public static string Button_Register {
            get {
                return ResourceManager.GetString("Button_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reload extensions ähnelt.
        /// </summary>
        public static string Button_ReloadExtensions {
            get {
                return ResourceManager.GetString("Button_ReloadExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        public static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select file path ähnelt.
        /// </summary>
        public static string Button_SelectFilePath {
            get {
                return ResourceManager.GetString("Button_SelectFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uninstall ähnelt.
        /// </summary>
        public static string Button_Uninstall {
            get {
                return ResourceManager.GetString("Button_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
        /// </summary>
        public static string Button_Update {
            get {
                return ResourceManager.GetString("Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage extensions ähnelt.
        /// </summary>
        public static string ExtensionsWindow_Title {
            get {
                return ResourceManager.GetString("ExtensionsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debug mode ähnelt.
        /// </summary>
        public static string Header_DebugMode {
            get {
                return ResourceManager.GetString("Header_DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string Header_Description {
            get {
                return ResourceManager.GetString("Header_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File path ähnelt.
        /// </summary>
        public static string Header_FilePath {
            get {
                return ResourceManager.GetString("Header_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GUID ähnelt.
        /// </summary>
        public static string Header_Guid {
            get {
                return ResourceManager.GetString("Header_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latest version ähnelt.
        /// </summary>
        public static string Header_LatestVersion {
            get {
                return ResourceManager.GetString("Header_LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Header_Name {
            get {
                return ResourceManager.GetString("Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Online ähnelt.
        /// </summary>
        public static string Header_Online {
            get {
                return ResourceManager.GetString("Header_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        public static string Header_Version {
            get {
                return ResourceManager.GetString("Header_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changes ähnelt.
        /// </summary>
        public static string Label_Changes {
            get {
                return ResourceManager.GetString("Label_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extension description ähnelt.
        /// </summary>
        public static string Label_ExtensionDescription {
            get {
                return ResourceManager.GetString("Label_ExtensionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extension name ähnelt.
        /// </summary>
        public static string Label_ExtensionName {
            get {
                return ResourceManager.GetString("Label_ExtensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installed extensions ähnelt.
        /// </summary>
        public static string Label_InstalledExtensions {
            get {
                return ResourceManager.GetString("Label_InstalledExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage local extensions ähnelt.
        /// </summary>
        public static string Label_ManageLocalExtensions {
            get {
                return ResourceManager.GetString("Label_ManageLocalExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        public static string Label_Version {
            get {
                return ResourceManager.GetString("Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The extension could not be added. Please check the log files for more information. ähnelt.
        /// </summary>
        public static string Message_AddExtension_Failed {
            get {
                return ResourceManager.GetString("Message_AddExtension_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The project could not be saved to: {0}. Please check the log files for more information. ähnelt.
        /// </summary>
        public static string Message_ProjectSaveFailed {
            get {
                return ResourceManager.GetString("Message_ProjectSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The extensions could not be reloaded in the project. Please check the log files for more information. ähnelt.
        /// </summary>
        public static string Message_ReloadExtensions_Failed {
            get {
                return ResourceManager.GetString("Message_ReloadExtensions_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following assemblies could not be unloaded: {0}. It is recommended to close the application and the project and then restart them. ähnelt.
        /// </summary>
        public static string Message_RemainingAssemblies {
            get {
                return ResourceManager.GetString("Message_RemainingAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following assemblies could not be unloaded: {0}. Do you want to save the project and reload it together with the application? (Recommended) ähnelt.
        /// </summary>
        public static string Message_RemainingAssemblies_RestartPrompt {
            get {
                return ResourceManager.GetString("Message_RemainingAssemblies_RestartPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following extensions could not be loaded: {0}. Please check the extensions and try again, or restart the application and the project. ähnelt.
        /// </summary>
        public static string Message_UnloadableExtensions {
            get {
                return ResourceManager.GetString("Message_UnloadableExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The extension could not be updated. Please check the log files for more information. ähnelt.
        /// </summary>
        public static string Message_UpdateExtension_Failed {
            get {
                return ResourceManager.GetString("Message_UpdateExtension_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installed ähnelt.
        /// </summary>
        public static string Tab_Installed {
            get {
                return ResourceManager.GetString("Tab_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offline ähnelt.
        /// </summary>
        public static string Tab_Offline {
            get {
                return ResourceManager.GetString("Tab_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Online ähnelt.
        /// </summary>
        public static string Tab_Online {
            get {
                return ResourceManager.GetString("Tab_Online", resourceCulture);
            }
        }
    }
}
