//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowBlox.UICore.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FlowBloxTaskManagementWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlowBloxTaskManagementWindow() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowBlox.UICore.Resources.FlowBloxTaskManagementWindow", typeof(FlowBloxTaskManagementWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project ähnelt.
        /// </summary>
        public static string Detail_Header {
            get {
                return ResourceManager.GetString("Detail_Header", resourceCulture);
            }
        }

        public static string Detail_Scheduling_Header {
            get {
                return ResourceManager.GetString("Detail_Scheduling_Header", resourceCulture);
            }
        }

        public static string Tab_Project {
            get {
                return ResourceManager.GetString("Tab_Project", resourceCulture);
            }
        }

        public static string Tab_InputParameters {
            get {
                return ResourceManager.GetString("Tab_InputParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task names must be unique. ähnelt.
        /// </summary>
        public static string Error_DuplicateTaskName {
            get {
                return ResourceManager.GetString("Error_DuplicateTaskName", resourceCulture);
            }
        }

        public static string Error_InvalidTaskName {
            get {
                return ResourceManager.GetString("Error_InvalidTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project could not be loaded. ähnelt.
        /// </summary>
        public static string Error_LoadProjectFailed {
            get {
                return ResourceManager.GetString("Error_LoadProjectFailed", resourceCulture);
            }
        }

        public static string Error_LoadInputParametersFailed {
            get {
                return ResourceManager.GetString("Error_LoadInputParametersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tasks could not be loaded. ähnelt.
        /// </summary>
        public static string Error_LoadTasksFailed {
            get {
                return ResourceManager.GetString("Error_LoadTasksFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A project file or Project Space GUID is required. ähnelt.
        /// </summary>
        public static string Error_ProjectReferenceMissing {
            get {
                return ResourceManager.GetString("Error_ProjectReferenceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task could not be started. ähnelt.
        /// </summary>
        public static string Error_RunTaskFailed {
            get {
                return ResourceManager.GetString("Error_RunTaskFailed", resourceCulture);
            }
        }

        public static string Error_StopTaskFailed {
            get {
                return ResourceManager.GetString("Error_StopTaskFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tasks could not be saved. ähnelt.
        /// </summary>
        public static string Error_SaveFailed {
            get {
                return ResourceManager.GetString("Error_SaveFailed", resourceCulture);
            }
        }

        public static string Error_TaskSchedulerPermissionDenied {
            get {
                return ResourceManager.GetString("Error_TaskSchedulerPermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Started sessions ähnelt.
        /// </summary>
        public static string Expander_Sessions_Header {
            get {
                return ResourceManager.GetString("Expander_Sessions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage FlowBlox project executions stored in the native Windows Task Scheduler folder &quot;\FlowBlox and contributors&quot;. ähnelt.
        /// </summary>
        public static string Header_Description_Main {
            get {
                return ResourceManager.GetString("Header_Description_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enabled ähnelt.
        /// </summary>
        public static string Header_Enabled {
            get {
                return ResourceManager.GetString("Header_Enabled", resourceCulture);
            }
        }

        public static string Header_Dirty {
            get {
                return ResourceManager.GetString("Header_Dirty", resourceCulture);
            }
        }

        public static string Header_Running {
            get {
                return ResourceManager.GetString("Header_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interval min. ähnelt.
        /// </summary>
        public static string Header_IntervalMinutes {
            get {
                return ResourceManager.GetString("Header_IntervalMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result ähnelt.
        /// </summary>
        public static string Header_LastResult {
            get {
                return ResourceManager.GetString("Header_LastResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next run ähnelt.
        /// </summary>
        public static string Header_NextRun {
            get {
                return ResourceManager.GetString("Header_NextRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schedule ähnelt.
        /// </summary>
        public static string Header_ScheduleType {
            get {
                return ResourceManager.GetString("Header_ScheduleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Created at ähnelt.
        /// </summary>
        public static string Header_SessionCreatedAt {
            get {
                return ResourceManager.GetString("Header_SessionCreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unique ID ähnelt.
        /// </summary>
        public static string Header_SessionId {
            get {
                return ResourceManager.GetString("Header_SessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log file ähnelt.
        /// </summary>
        public static string Header_SessionLogFile {
            get {
                return ResourceManager.GetString("Header_SessionLogFile", resourceCulture);
            }
        }

        public static string Header_SessionMessage {
            get {
                return ResourceManager.GetString("Header_SessionMessage", resourceCulture);
            }
        }

        public static string Header_SessionStatus {
            get {
                return ResourceManager.GetString("Header_SessionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        public static string Header_StartAt {
            get {
                return ResourceManager.GetString("Header_StartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task name ähnelt.
        /// </summary>
        public static string Header_TaskName {
            get {
                return ResourceManager.GetString("Header_TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scheduled project executions ähnelt.
        /// </summary>
        public static string Header_Title_Main {
            get {
                return ResourceManager.GetString("Header_Title_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project name ähnelt.
        /// </summary>
        public static string Label_ProjectName {
            get {
                return ResourceManager.GetString("Label_ProjectName", resourceCulture);
            }
        }

        public static string Label_IntervalMinutes {
            get {
                return ResourceManager.GetString("Label_IntervalMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference ähnelt.
        /// </summary>
        public static string Label_ProjectReference {
            get {
                return ResourceManager.GetString("Label_ProjectReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task directory ähnelt.
        /// </summary>
        public static string Label_TaskDirectory {
            get {
                return ResourceManager.GetString("Label_TaskDirectory", resourceCulture);
            }
        }

        public static string Label_ScheduleType {
            get {
                return ResourceManager.GetString("Label_ScheduleType", resourceCulture);
            }
        }

        public static string Label_StartAt {
            get {
                return ResourceManager.GetString("Label_StartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task changes were saved. ähnelt.
        /// </summary>
        public static string Message_SaveSuccessful {
            get {
                return ResourceManager.GetString("Message_SaveSuccessful", resourceCulture);
            }
        }

        public static string Message_DiscardChangesQuestion {
            get {
                return ResourceManager.GetString("Message_DiscardChangesQuestion", resourceCulture);
            }
        }

        public static string Message_SaveBeforeRun {
            get {
                return ResourceManager.GetString("Message_SaveBeforeRun", resourceCulture);
            }
        }

        public static string Message_SaveBeforeStop {
            get {
                return ResourceManager.GetString("Message_SaveBeforeStop", resourceCulture);
            }
        }

        public static string Message_TaskAlreadyRunning {
            get {
                return ResourceManager.GetString("Message_TaskAlreadyRunning", resourceCulture);
            }
        }

        public static string Message_TaskNotRunning {
            get {
                return ResourceManager.GetString("Message_TaskNotRunning", resourceCulture);
            }
        }

        public static string Message_LoadingInputParameters {
            get {
                return ResourceManager.GetString("Message_LoadingInputParameters", resourceCulture);
            }
        }

        public static string Message_InputParametersLoadPrompt {
            get {
                return ResourceManager.GetString("Message_InputParametersLoadPrompt", resourceCulture);
            }
        }

        public static string Message_NoInputParameters {
            get {
                return ResourceManager.GetString("Message_NoInputParameters", resourceCulture);
            }
        }

        public static string Toggle_On {
            get {
                return ResourceManager.GetString("Toggle_On", resourceCulture);
            }
        }

        public static string Toggle_Off {
            get {
                return ResourceManager.GetString("Toggle_Off", resourceCulture);
            }
        }

        public static string SessionMessage_Running {
            get {
                return ResourceManager.GetString("SessionMessage_Running", resourceCulture);
            }
        }

        public static string SessionMessage_Successful {
            get {
                return ResourceManager.GetString("SessionMessage_Successful", resourceCulture);
            }
        }

        public static string SessionStatus_Failed {
            get {
                return ResourceManager.GetString("SessionStatus_Failed", resourceCulture);
            }
        }

        public static string SessionStatus_Running {
            get {
                return ResourceManager.GetString("SessionStatus_Running", resourceCulture);
            }
        }

        public static string SessionStatus_Successful {
            get {
                return ResourceManager.GetString("SessionStatus_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scheduled FlowBlox tasks ähnelt.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Link project by project file ähnelt.
        /// </summary>
        public static string Tooltip_AddProjectFile {
            get {
                return ResourceManager.GetString("Tooltip_AddProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Link project by Project Space ähnelt.
        /// </summary>
        public static string Tooltip_AddProjectSpace {
            get {
                return ResourceManager.GetString("Tooltip_AddProjectSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply changes ähnelt.
        /// </summary>
        public static string Tooltip_Apply {
            get {
                return ResourceManager.GetString("Tooltip_Apply", resourceCulture);
            }
        }

        public static string Tooltip_IntervalMinutes {
            get {
                return ResourceManager.GetString("Tooltip_IntervalMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open session directory ähnelt.
        /// </summary>
        public static string Tooltip_OpenSessionDirectory {
            get {
                return ResourceManager.GetString("Tooltip_OpenSessionDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open session log file ähnelt.
        /// </summary>
        public static string Tooltip_OpenSessionLog {
            get {
                return ResourceManager.GetString("Tooltip_OpenSessionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open task directory ähnelt.
        /// </summary>
        public static string Tooltip_OpenTaskDirectory {
            get {
                return ResourceManager.GetString("Tooltip_OpenTaskDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reload tasks ähnelt.
        /// </summary>
        public static string Tooltip_Reload {
            get {
                return ResourceManager.GetString("Tooltip_Reload", resourceCulture);
            }
        }

        public static string Tooltip_RefreshSessions {
            get {
                return ResourceManager.GetString("Tooltip_RefreshSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove selected task ähnelt.
        /// </summary>
        public static string Tooltip_RemoveTask {
            get {
                return ResourceManager.GetString("Tooltip_RemoveTask", resourceCulture);
            }
        }

        public static string Tooltip_ScheduleType {
            get {
                return ResourceManager.GetString("Tooltip_ScheduleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run selected task now ähnelt.
        /// </summary>
        public static string Tooltip_RunTask {
            get {
                return ResourceManager.GetString("Tooltip_RunTask", resourceCulture);
            }
        }

        public static string Tooltip_StopTask {
            get {
                return ResourceManager.GetString("Tooltip_StopTask", resourceCulture);
            }
        }

        public static string Tooltip_StartAt {
            get {
                return ResourceManager.GetString("Tooltip_StartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable or disable selected task ähnelt.
        /// </summary>
        public static string Tooltip_ToggleEnabled {
            get {
                return ResourceManager.GetString("Tooltip_ToggleEnabled", resourceCulture);
            }
        }
    }
}
