//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowBlox.UICore.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ManagedObjectsView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ManagedObjectsView() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowBlox.UICore.Resources.ManagedObjectsView", typeof(ManagedObjectsView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties ähnelt.
        /// </summary>
        public static string Col_DisplayableProperties {
            get {
                return ResourceManager.GetString("Col_DisplayableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Col_Name {
            get {
                return ResourceManager.GetString("Col_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Used In ähnelt.
        /// </summary>
        public static string Col_UsedIn {
            get {
                return ResourceManager.GetString("Col_UsedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        public static string DisplayableProperties_None {
            get {
                return ResourceManager.GetString("DisplayableProperties_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No managed objects are available for the selected category. ähnelt.
        /// </summary>
        public static string EmptyState_NoManagedObjects {
            get {
                return ResourceManager.GetString("EmptyState_NoManagedObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No default constructor is available for &apos;{0}&apos;. ähnelt.
        /// </summary>
        public static string Message_CannotCreateInstance_Description {
            get {
                return ResourceManager.GetString("Message_CannotCreateInstance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creation not possible ähnelt.
        /// </summary>
        public static string Message_CannotCreateInstance_Title {
            get {
                return ResourceManager.GetString("Message_CannotCreateInstance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The managed object &apos;{0}&apos; is still used in: {1} ähnelt.
        /// </summary>
        public static string Message_DeleteBlocked_Description {
            get {
                return ResourceManager.GetString("Message_DeleteBlocked_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete blocked ähnelt.
        /// </summary>
        public static string Message_DeleteBlocked_Title {
            get {
                return ResourceManager.GetString("Message_DeleteBlocked_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete &apos;{0}&apos;? ähnelt.
        /// </summary>
        public static string Message_DeleteConfirm_Description {
            get {
                return ResourceManager.GetString("Message_DeleteConfirm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete managed object ähnelt.
        /// </summary>
        public static string Message_DeleteConfirm_Title {
            get {
                return ResourceManager.GetString("Message_DeleteConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Managed Objects ähnelt.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actions ähnelt.
        /// </summary>
        public static string Toolbar_Actions {
            get {
                return ResourceManager.GetString("Toolbar_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add managed object ähnelt.
        /// </summary>
        public static string Toolbar_Add_Tooltip {
            get {
                return ResourceManager.GetString("Toolbar_Add_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete managed object ähnelt.
        /// </summary>
        public static string Toolbar_Delete_Tooltip {
            get {
                return ResourceManager.GetString("Toolbar_Delete_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit managed object ähnelt.
        /// </summary>
        public static string Toolbar_Edit_Tooltip {
            get {
                return ResourceManager.GetString("Toolbar_Edit_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        /// </summary>
        public static string Toolbar_Refresh_Tooltip {
            get {
                return ResourceManager.GetString("Toolbar_Refresh_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Additional Managed Objects ähnelt.
        /// </summary>
        public static string Tree_UncategorizedManagedObjects {
            get {
                return ResourceManager.GetString("Tree_UncategorizedManagedObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        public static string UsedIn_None {
            get {
                return ResourceManager.GetString("UsedIn_None", resourceCulture);
            }
        }
    }
}
