//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowBlox.UICore.Resources {
    using System;


    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectPanel {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectPanel() {
        }

        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowBlox.UICore.Resources.ProjectPanel", typeof(ProjectPanel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle Ressourcenzuordnungen.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove breakpoint ähnelt.
        /// </summary>
        public static string ContextMenu_RemoveBreakpoint {
            get {
                return ResourceManager.GetString("ContextMenu_RemoveBreakpoint", resourceCulture);
            }
        }

        public static string ArrowLabel_RecursiveCall {
            get {
                return ResourceManager.GetString("ArrowLabel_RecursiveCall", resourceCulture);
            }
        }

        public static string AssignFlowBlockName_Description {
            get {
                return ResourceManager.GetString("AssignFlowBlockName_Description", resourceCulture);
            }
        }

        public static string AssignFlowBlockName_Title {
            get {
                return ResourceManager.GetString("AssignFlowBlockName_Title", resourceCulture);
            }
        }

        public static string ContextMenu_CopyValue {
            get {
                return ResourceManager.GetString("ContextMenu_CopyValue", resourceCulture);
            }
        }

        public static string ContextMenu_DefineExecutionIndex {
            get {
                return ResourceManager.GetString("ContextMenu_DefineExecutionIndex", resourceCulture);
            }
        }

        public static string ContextMenu_DeleteFlowBlock {
            get {
                return ResourceManager.GetString("ContextMenu_DeleteFlowBlock", resourceCulture);
            }
        }

        public static string ContextMenu_EditProperties {
            get {
                return ResourceManager.GetString("ContextMenu_EditProperties", resourceCulture);
            }
        }

        public static string ContextMenu_ManageExecutionIndex {
            get {
                return ResourceManager.GetString("ContextMenu_ManageExecutionIndex", resourceCulture);
            }
        }

        public static string ContextMenu_ManageNotifications {
            get {
                return ResourceManager.GetString("ContextMenu_ManageNotifications", resourceCulture);
            }
        }

        public static string ContextMenu_Refresh {
            get {
                return ResourceManager.GetString("ContextMenu_Refresh", resourceCulture);
            }
        }

        public static string ContextMenu_RemoveConnection {
            get {
                return ResourceManager.GetString("ContextMenu_RemoveConnection", resourceCulture);
            }
        }

        public static string ContextMenu_RemoveExecutionIndex {
            get {
                return ResourceManager.GetString("ContextMenu_RemoveExecutionIndex", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set breakpoint ähnelt.
        /// </summary>
        public static string ContextMenu_SetBreakpoint {
            get {
                return ResourceManager.GetString("ContextMenu_SetBreakpoint", resourceCulture);
            }
        }

        public static string ContextMenu_ShowInputDatasets {
            get {
                return ResourceManager.GetString("ContextMenu_ShowInputDatasets", resourceCulture);
            }
        }

        public static string ContextMenu_ShowOutputDatasets {
            get {
                return ResourceManager.GetString("ContextMenu_ShowOutputDatasets", resourceCulture);
            }
        }

        public static string ContextMenu_ViewProperties {
            get {
                return ResourceManager.GetString("ContextMenu_ViewProperties", resourceCulture);
            }
        }

        public static string Legend_IterationContext {
            get {
                return ResourceManager.GetString("Legend_IterationContext", resourceCulture);
            }
        }

        public static string Legend_Invoke {
            get {
                return ResourceManager.GetString("Legend_Invoke", resourceCulture);
            }
        }

        public static string Legend_RecursiveCall {
            get {
                return ResourceManager.GetString("Legend_RecursiveCall", resourceCulture);
            }
        }

        public static string Toolbar_AutoLayout {
            get {
                return ResourceManager.GetString("Toolbar_AutoLayout", resourceCulture);
            }
        }

        public static string Toolbar_Connect {
            get {
                return ResourceManager.GetString("Toolbar_Connect", resourceCulture);
            }
        }

        public static string Toolbar_Execute {
            get {
                return ResourceManager.GetString("Toolbar_Execute", resourceCulture);
            }
        }

        public static string Toolbar_Pause {
            get {
                return ResourceManager.GetString("Toolbar_Pause", resourceCulture);
            }
        }

        public static string Toolbar_Refresh {
            get {
                return ResourceManager.GetString("Toolbar_Refresh", resourceCulture);
            }
        }

        public static string Toolbar_Select {
            get {
                return ResourceManager.GetString("Toolbar_Select", resourceCulture);
            }
        }

        public static string Toolbar_SelectAll {
            get {
                return ResourceManager.GetString("Toolbar_SelectAll", resourceCulture);
            }
        }

        public static string Toolbar_SelectDown {
            get {
                return ResourceManager.GetString("Toolbar_SelectDown", resourceCulture);
            }
        }

        public static string Toolbar_SelectLeft {
            get {
                return ResourceManager.GetString("Toolbar_SelectLeft", resourceCulture);
            }
        }

        public static string Toolbar_SelectRight {
            get {
                return ResourceManager.GetString("Toolbar_SelectRight", resourceCulture);
            }
        }

        public static string Toolbar_SelectUp {
            get {
                return ResourceManager.GetString("Toolbar_SelectUp", resourceCulture);
            }
        }

        public static string Toolbar_Settings {
            get {
                return ResourceManager.GetString("Toolbar_Settings", resourceCulture);
            }
        }

        public static string Toolbar_Stop {
            get {
                return ResourceManager.GetString("Toolbar_Stop", resourceCulture);
            }
        }
    }
}
