//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowBlox.UICore.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegistrationWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegistrationWindow() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowBlox.UICore.Resources.RegistrationWindow", typeof(RegistrationWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        public static string Button_Back {
            get {
                return ResourceManager.GetString("Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register ähnelt.
        /// </summary>
        public static string Button_Register {
            get {
                return ResourceManager.GetString("Button_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Captcha konnte nicht geladen werden. Bitte versuchen Sie es erneut. ähnelt.
        /// </summary>
        public static string Error_LoadCaptchaFailed {
            get {
                return ResourceManager.GetString("Error_LoadCaptchaFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter your details to create a new account. Required fields are marked with an asterisk (*). ähnelt.
        /// </summary>
        public static string Header_Description {
            get {
                return ResourceManager.GetString("Header_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registration ähnelt.
        /// </summary>
        public static string Header_Title {
            get {
                return ResourceManager.GetString("Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Captcha ähnelt.
        /// </summary>
        public static string Label_Captcha {
            get {
                return ResourceManager.GetString("Label_Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the captcha code: ähnelt.
        /// </summary>
        public static string Label_CaptchaCode {
            get {
                return ResourceManager.GetString("Label_CaptchaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email ähnelt.
        /// </summary>
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repeat email ähnelt.
        /// </summary>
        public static string Label_EmailRepeat {
            get {
                return ResourceManager.GetString("Label_EmailRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First name ähnelt.
        /// </summary>
        public static string Label_FirstName {
            get {
                return ResourceManager.GetString("Label_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last name ähnelt.
        /// </summary>
        public static string Label_LastName {
            get {
                return ResourceManager.GetString("Label_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repeat password ähnelt.
        /// </summary>
        public static string Label_PasswordRepeat {
            get {
                return ResourceManager.GetString("Label_PasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        public static string Label_UserName {
            get {
                return ResourceManager.GetString("Label_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The email address &quot;{0}&quot; already exists. ähnelt.
        /// </summary>
        public static string Message_EmailExists {
            get {
                return ResourceManager.GetString("Message_EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email addresses do not match. ähnelt.
        /// </summary>
        public static string Message_EmailMismatch {
            get {
                return ResourceManager.GetString("Message_EmailMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The CAPTCHA is invalid or has expired. Please try again. ähnelt.
        /// </summary>
        public static string Message_InvalidCaptcha {
            get {
                return ResourceManager.GetString("Message_InvalidCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwords do not match. ähnelt.
        /// </summary>
        public static string Message_PasswordMismatch {
            get {
                return ResourceManager.GetString("Message_PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service error: ähnelt.
        /// </summary>
        public static string Message_ServiceError {
            get {
                return ResourceManager.GetString("Message_ServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registration successful. Please check your email and confirm your account to complete the registration. ähnelt.
        /// </summary>
        public static string Message_Success {
            get {
                return ResourceManager.GetString("Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optional ähnelt.
        /// </summary>
        public static string Placeholder_FirstName {
            get {
                return ResourceManager.GetString("Placeholder_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optional ähnelt.
        /// </summary>
        public static string Placeholder_LastName {
            get {
                return ResourceManager.GetString("Placeholder_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optional (auto-generated if omitted) ähnelt.
        /// </summary>
        public static string Placeholder_UserName {
            get {
                return ResourceManager.GetString("Placeholder_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register ähnelt.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optional. If no username is provided, one will be generated automatically. ähnelt.
        /// </summary>
        public static string Tooltip_UserName {
            get {
                return ResourceManager.GetString("Tooltip_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The username &quot;{0}&quot; already exists. ähnelt.
        /// </summary>
        public static string UsernameExists {
            get {
                return ResourceManager.GetString("UsernameExists", resourceCulture);
            }
        }
    }
}
