//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowBlox.UICore.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestDefinitionView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestDefinitionView() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowBlox.UICore.Resources.TestDefinitionView", typeof(TestDefinitionView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        public static string Button_Back {
            get {
                return ResourceManager.GetString("Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Execute ähnelt.
        /// </summary>
        public static string Button_Execute {
            get {
                return ResourceManager.GetString("Button_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expectation target ähnelt.
        /// </summary>
        public static string Column_ExpectationTarget {
            get {
                return ResourceManager.GetString("Column_ExpectationTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index ähnelt.
        /// </summary>
        public static string Column_Index {
            get {
                return ResourceManager.GetString("Column_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comparison operator ähnelt.
        /// </summary>
        public static string Column_Operator {
            get {
                return ResourceManager.GetString("Column_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        public static string Column_Value {
            get {
                return ResourceManager.GetString("Column_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generator notes ähnelt.
        /// </summary>
        public static string Expander_GeneratorHints_Header {
            get {
                return ResourceManager.GetString("Expander_GeneratorHints_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic regeneration during runtime start is only performed when this test case is marked as &quot;Required for runtime execution&quot; and generation strategies exist on the affected flow block. ähnelt.
        /// </summary>
        public static string Expander_GeneratorHints_Note1 {
            get {
                return ResourceManager.GetString("Expander_GeneratorHints_Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimum at the target flow block: define at least two expectations, one for the value and one for the dataset count. ähnelt.
        /// </summary>
        public static string Expander_GeneratorHints_Note2 {
            get {
                return ResourceManager.GetString("Expander_GeneratorHints_Note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recommended value expectation: use target &quot;First value&quot; or &quot;Any value&quot; and comparison &quot;equals&quot; with the expected value. ähnelt.
        /// </summary>
        public static string Expander_GeneratorHints_Note3 {
            get {
                return ResourceManager.GetString("Expander_GeneratorHints_Note3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Required count expectation: use target &quot;Number of datasets&quot; and comparison &quot;equals&quot; with the expected count. More expectation conditions usually improve generator output quality. ähnelt.
        /// </summary>
        public static string Expander_GeneratorHints_Note4 {
            get {
                return ResourceManager.GetString("Expander_GeneratorHints_Note4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tip: Instead of &quot;Any value&quot;, you can use selection mode &quot;User input expected&quot;. This combines expectation and selection when downstream flow blocks should be executed. ähnelt.
        /// </summary>
        public static string Expander_GeneratorHints_Note5 {
            get {
                return ResourceManager.GetString("Expander_GeneratorHints_Note5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test cases and test expectations can be used by generators to derive targeted values based on a failed test case. ähnelt.
        /// </summary>
        public static string Expander_GeneratorHints_Text {
            get {
                return ResourceManager.GetString("Expander_GeneratorHints_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test case guidance ähnelt.
        /// </summary>
        public static string Expander_TestCaseHelp_Header {
            get {
                return ResourceManager.GetString("Expander_TestCaseHelp_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A test case can be executed in the flow block context and from the test view. If no current flow block is passed, the last assigned target flow block is used. ähnelt.
        /// </summary>
        public static string Expander_TestCaseHelp_Note1 {
            get {
                return ResourceManager.GetString("Expander_TestCaseHelp_Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Important: If a preceding flow block is not executed, set required field values manually so downstream checks can run reliably. ähnelt.
        /// </summary>
        public static string Expander_TestCaseHelp_Note2 {
            get {
                return ResourceManager.GetString("Expander_TestCaseHelp_Note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use an automatic selection mode when values should be determined from flow block execution. ähnelt.
        /// </summary>
        public static string Expander_TestCaseHelp_Note3 {
            get {
                return ResourceManager.GetString("Expander_TestCaseHelp_Note3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expectations are evaluated per field. If an expectation is not met, the test fails. Set &quot;Required for runtime execution&quot; only when this test should run automatically at runtime start. ähnelt.
        /// </summary>
        public static string Expander_TestCaseHelp_Note4 {
            get {
                return ResourceManager.GetString("Expander_TestCaseHelp_Note4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log level ähnelt.
        /// </summary>
        public static string GridViewColumn_LogLevel {
            get {
                return ResourceManager.GetString("GridViewColumn_LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message ähnelt.
        /// </summary>
        public static string GridViewColumn_Message {
            get {
                return ResourceManager.GetString("GridViewColumn_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timestamp ähnelt.
        /// </summary>
        public static string GridViewColumn_Timestamp {
            get {
                return ResourceManager.GetString("GridViewColumn_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A test case describes a complete test run from the first executed flow block to the current or last assigned target flow block. If a flow block is executed, its activation requirements must be fulfilled, for example required field values and activation conditions. Required values to be set are marked, and additional guidance is available in the expanders below. ähnelt.
        /// </summary>
        public static string Header_Description_Main {
            get {
                return ResourceManager.GetString("Header_Description_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test case configuration ähnelt.
        /// </summary>
        public static string Header_Title_Main {
            get {
                return ResourceManager.GetString("Header_Title_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This test configuration is required for execution. ähnelt.
        /// </summary>
        public static string Icon_UIRequiredForExecution_FieldConfiguration_Tooltip {
            get {
                return ResourceManager.GetString("Icon_UIRequiredForExecution_FieldConfiguration_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This test dataset is required for execution. ähnelt.
        /// </summary>
        public static string Icon_UIRequiredForExecution_TestDataset_Tooltip {
            get {
                return ResourceManager.GetString("Icon_UIRequiredForExecution_TestDataset_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Required for runtime execution ähnelt.
        /// </summary>
        public static string Label_RequiredForExecution {
            get {
                return ResourceManager.GetString("Label_RequiredForExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selected test configuration ähnelt.
        /// </summary>
        public static string Label_SelectedConfiguration {
            get {
                return ResourceManager.GetString("Label_SelectedConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open in editor ähnelt.
        /// </summary>
        public static string MenuItem_OpenInEditor {
            get {
                return ResourceManager.GetString("MenuItem_OpenInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The runtime could not be started.
        ///
        ///Message(s):
        ///{0} ähnelt.
        /// </summary>
        public static string Message_RuntimeInitializationFailed {
            get {
                return ResourceManager.GetString("Message_RuntimeInitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A test configuration can be defined for each field. ähnelt.
        /// </summary>
        public static string StackPanel_SelectedConfiguration_Tooltip {
            get {
                return ResourceManager.GetString("StackPanel_SelectedConfiguration_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test expectations ähnelt.
        /// </summary>
        public static string TabItem_Expectations {
            get {
                return ResourceManager.GetString("TabItem_Expectations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Runtime logs ähnelt.
        /// </summary>
        public static string TabItem_RuntimeLogs {
            get {
                return ResourceManager.GetString("TabItem_RuntimeLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test results ähnelt.
        /// </summary>
        public static string TabItem_TestResults {
            get {
                return ResourceManager.GetString("TabItem_TestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Execute ähnelt.
        /// </summary>
        public static string Text_Execute {
            get {
                return ResourceManager.GetString("Text_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Field label ähnelt.
        /// </summary>
        public static string Text_FieldLabel {
            get {
                return ResourceManager.GetString("Text_FieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flow block ähnelt.
        /// </summary>
        public static string Text_FlowBlock {
            get {
                return ResourceManager.GetString("Text_FlowBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selection mode ähnelt.
        /// </summary>
        public static string Text_SelectionMode {
            get {
                return ResourceManager.GetString("Text_SelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the index... ähnelt.
        /// </summary>
        public static string Text_SelectionMode_Index_Watermark {
            get {
                return ResourceManager.GetString("Text_SelectionMode_Index_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To determine a field value automatically from a flow block execution, use a selection mode from the &quot;Automatic selection&quot; category. To define a selection and an expectation at the same time, use &quot;User input expected&quot;. To set a value manually (for example without execution) for a field, use &quot;Manual input&quot;. ähnelt.
        /// </summary>
        public static string Text_SelectionMode_InfoTooltip {
            get {
                return ResourceManager.GetString("Text_SelectionMode_InfoTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test expectations ähnelt.
        /// </summary>
        public static string Text_TestExpectations {
            get {
                return ResourceManager.GetString("Text_TestExpectations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User input / field value ähnelt.
        /// </summary>
        public static string Text_UserInputFieldValue {
            get {
                return ResourceManager.GetString("Text_UserInputFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test definition ähnelt.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string Toolbar_Add {
            get {
                return ResourceManager.GetString("Toolbar_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        public static string Toolbar_Delete {
            get {
                return ResourceManager.GetString("Toolbar_Delete", resourceCulture);
            }
        }
    }
}
