//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowBlox.UICore.PopUp.Resources
{
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OnnxGenAIPopUpTexts
    {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OnnxGenAIPopUpTexts()
        {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowBlox.UICore.PopUp.Resources.OnnxGenAIPopUpTexts", typeof(OnnxGenAIPopUpTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Python is required to download the prepared model package. Download the latest release here and enable “Add Python to PATH” during setup:
        ///https://www.python.org/downloads/ ähnelt.
        /// </summary>
        public static string Step1_Description
        {
            get
            {
                return ResourceManager.GetString("Step1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install Python ähnelt.
        /// </summary>
        public static string Step1_Headline
        {
            get
            {
                return ResourceManager.GetString("Step1_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open the included page, copy the ready-to-run Python script, save it as a .py file, and run it. The CPU INT4 model is about 10.9 GB and is stored next to the script under onnxgenai\phi-4:
        ///{0} ähnelt.
        /// </summary>
        public static string Step2_Description
        {
            get
            {
                return ResourceManager.GetString("Step2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download the Phi-4 ONNX GenAI model ähnelt.
        /// </summary>
        public static string Step2_Headline
        {
            get
            {
                return ResourceManager.GetString("Step2_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set ModelFolder to the generated onnxgenai\phi-4 directory. It must contain genai_config.json, tokenizer.json, model.onnx, model.onnx.data, and the additional tokenizer assets downloaded by the script. ähnelt.
        /// </summary>
        public static string Step3_Description
        {
            get
            {
                return ResourceManager.GetString("Step3_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the completed model folder ähnelt.
        /// </summary>
        public static string Step3_Headline
        {
            get
            {
                return ResourceManager.GetString("Step3_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set up ONNX GenAI text generation ähnelt.
        /// </summary>
        public static string Window_Title
        {
            get
            {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
    }
}
