//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowBlox {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FlowBloxMainUITexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlowBloxMainUITexts() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowBlox.FlowBloxMainUITexts", typeof(FlowBloxMainUITexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Produktinformationen ähnelt.
        /// </summary>
        internal static string About_groupBoxProductInformation_Text {
            get {
                return ResourceManager.GetString("About_groupBoxProductInformation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Informationen über FlowBlox ähnelt.
        /// </summary>
        internal static string About_Text {
            get {
                return ResourceManager.GetString("About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie das Projekt &quot;{0}&quot; wirklich schließen? ähnelt.
        /// </summary>
        internal static string AppWindow_CloseProjectConfirm_Message {
            get {
                return ResourceManager.GetString("AppWindow_CloseProjectConfirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt schließen? ähnelt.
        /// </summary>
        internal static string AppWindow_CloseProjectConfirm_Title {
            get {
                return ResourceManager.GetString("AppWindow_CloseProjectConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte melden Sie diesen Fehler an https://www.flowblox.net/. ähnelt.
        /// </summary>
        internal static string AppWindow_ErrorReport_Message {
            get {
                return ResourceManager.GetString("AppWindow_ErrorReport_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FlowBlox Fehlerbericht ähnelt.
        /// </summary>
        internal static string AppWindow_ErrorReport_Title {
            get {
                return ResourceManager.GetString("AppWindow_ErrorReport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konnte das aktuelle FlowBlox.Grid nicht als Bitmap (*.bmp) exportieren. Bitte überprüfen Sie die Logfiles, um weitere Informationen zu erhalten. ähnelt.
        /// </summary>
        internal static string AppWindow_GridExportFailed_Message {
            get {
                return ResourceManager.GetString("AppWindow_GridExportFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FlowBlox.Grid: Problem beim Exportieren ähnelt.
        /// </summary>
        internal static string AppWindow_GridExportFailed_Title {
            get {
                return ResourceManager.GetString("AppWindow_GridExportFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I&amp;nfo über FlowBlox ähnelt.
        /// </summary>
        internal static string AppWindow_itmAbout_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmAbout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt sch&amp;ließen ähnelt.
        /// </summary>
        internal static string AppWindow_itmCloseProject_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmCloseProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Kopieren ähnelt.
        /// </summary>
        internal static string AppWindow_itmCopy_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmCopy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Projekt &amp;erstellen ähnelt.
        /// </summary>
        internal static string AppWindow_itmCreateProject_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmCreateProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Element &amp;entfernen ähnelt.
        /// </summary>
        internal static string AppWindow_itmDeleteElement_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmDeleteElement_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Andockbare Dialoge ähnelt.
        /// </summary>
        internal static string AppWindow_itmDockablePanels_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmDockablePanels_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigenschaften &amp;bearbeiten ähnelt.
        /// </summary>
        internal static string AppWindow_itmEditProject_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmEditProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Lizenz ähnelt.
        /// </summary>
        internal static string AppWindow_itmLicense_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmLicense_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anmelden ähnelt.
        /// </summary>
        internal static string AppWindow_itmLogin_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmLogin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abmelden ähnelt.
        /// </summary>
        internal static string AppWindow_itmLogout_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmLogout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lizenzverwaltung ähnelt.
        /// </summary>
        internal static string AppWindow_itmManageLicenses_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmManageLicenses_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überwachung ähnelt.
        /// </summary>
        internal static string AppWindow_itmMonitor_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmMonitor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anwendung-Logfile(s) anzeigen ähnelt.
        /// </summary>
        internal static string AppWindow_itmOpenApplicationLogDirectory_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmOpenApplicationLogDirectory_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgabeverzeichnis ö&amp;ffnen ähnelt.
        /// </summary>
        internal static string AppWindow_itmOpenOutputDir_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmOpenOutputDir_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt ö&amp;ffnen ähnelt.
        /// </summary>
        internal static string AppWindow_itmOpenProject_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmOpenProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projektverzeichnis öff&amp;nen ähnelt.
        /// </summary>
        internal static string AppWindow_itmOpenProjectDir_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmOpenProjectDir_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laufzeit-Logfile(s) anzeigen ähnelt.
        /// </summary>
        internal static string AppWindow_itmOpenRuntimeLogDirectory_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmOpenRuntimeLogDirectory_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Optionen... ähnelt.
        /// </summary>
        internal static string AppWindow_itmOptions_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmOptions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Einfügen ähnelt.
        /// </summary>
        internal static string AppWindow_itmPaste_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmPaste_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beenden ähnelt.
        /// </summary>
        internal static string AppWindow_itmQuitApplication_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmQuitApplication_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Wiederholen ähnelt.
        /// </summary>
        internal static string AppWindow_itmRedo_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmRedo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registrieren ähnelt.
        /// </summary>
        internal static string AppWindow_itmRegister_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmRegister_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Problem melden ähnelt.
        /// </summary>
        internal static string AppWindow_itmReportProblem_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmReportProblem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt &amp;speichern unter ähnelt.
        /// </summary>
        internal static string AppWindow_itmSaveAs_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmSaveAs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt &amp;speichern ähnelt.
        /// </summary>
        internal static string AppWindow_itmSaveProject_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmSaveProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Toolbox ähnelt.
        /// </summary>
        internal static string AppWindow_itmToolbox_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmToolbox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Rückgängig ähnelt.
        /// </summary>
        internal static string AppWindow_itmUndo_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmUndo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Benutzerdefinierte Felder ähnelt.
        /// </summary>
        internal static string AppWindow_itmUserFields_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmUserFields_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account ähnelt.
        /// </summary>
        internal static string AppWindow_mnItmAccount_Text {
            get {
                return ResourceManager.GetString("AppWindow_mnItmAccount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Bearbeiten ähnelt.
        /// </summary>
        internal static string AppWindow_mnItmEdit_Text {
            get {
                return ResourceManager.GetString("AppWindow_mnItmEdit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Hilfe ähnelt.
        /// </summary>
        internal static string AppWindow_mnItmHelp_Text {
            get {
                return ResourceManager.GetString("AppWindow_mnItmHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Extras ähnelt.
        /// </summary>
        internal static string AppWindow_mnItmMisc_Text {
            get {
                return ResourceManager.GetString("AppWindow_mnItmMisc_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Projekt ähnelt.
        /// </summary>
        internal static string AppWindow_mnItmProject_Text {
            get {
                return ResourceManager.GetString("AppWindow_mnItmProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Fenster ähnelt.
        /// </summary>
        internal static string AppWindow_mnItmWindows_Text {
            get {
                return ResourceManager.GetString("AppWindow_mnItmWindows_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie das Projekt &quot;{0}&quot; wirklich schließen und ein neues Projekt erstellen? ähnelt.
        /// </summary>
        internal static string AppWindow_NewProjectConfirm_Message {
            get {
                return ResourceManager.GetString("AppWindow_NewProjectConfirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Projekt erstellen? ähnelt.
        /// </summary>
        internal static string AppWindow_NewProjectConfirm_Title {
            get {
                return ResourceManager.GetString("AppWindow_NewProjectConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie das Projekt &quot;{0}&quot; wirklich schließen und ein anderes Projekt laden? ähnelt.
        /// </summary>
        internal static string AppWindow_OpenProjectConfirm_Message {
            get {
                return ResourceManager.GetString("AppWindow_OpenProjectConfirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Projekt laden? ähnelt.
        /// </summary>
        internal static string AppWindow_OpenProjectConfirm_Title {
            get {
                return ResourceManager.GetString("AppWindow_OpenProjectConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Seite konnte nicht geöffnet werden: {0} ähnelt.
        /// </summary>
        internal static string AppWindow_OpenUrlFailed_Message {
            get {
                return ResourceManager.GetString("AppWindow_OpenUrlFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seite konnte nicht geöffnet werden ähnelt.
        /// </summary>
        internal static string AppWindow_OpenUrlFailed_Title {
            get {
                return ResourceManager.GetString("AppWindow_OpenUrlFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Projekt konnte nicht vollständig geladen werden. Beim Schließen dieses Fensters wird automatisch ein Fehlerbericht generiert. Bitte prüfen Sie zusätzlich die Logdateien, um weitere Details zu den Ursachen des Problems zu erhalten.
        ///   ähnelt.
        /// </summary>
        internal static string AppWindow_ProjectLoadFailed_Message {
            get {
                return ResourceManager.GetString("AppWindow_ProjectLoadFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt nicht vollständig geladen ähnelt.
        /// </summary>
        internal static string AppWindow_ProjectLoadFailed_Title {
            get {
                return ResourceManager.GetString("AppWindow_ProjectLoadFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinweis beim Öffnen ähnelt.
        /// </summary>
        internal static string AppWindow_ProjectNotice_Title {
            get {
                return ResourceManager.GetString("AppWindow_ProjectNotice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte halten Sie erst die aktuelle Ausführung an, bevor Sie FlowBlox schließen. ähnelt.
        /// </summary>
        internal static string AppWindow_RuntimeActiveClose_Message {
            get {
                return ResourceManager.GetString("AppWindow_RuntimeActiveClose_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Achtung: Laufzeit aktiv ähnelt.
        /// </summary>
        internal static string AppWindow_RuntimeActiveClose_Title {
            get {
                return ResourceManager.GetString("AppWindow_RuntimeActiveClose_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie die Änderungen an dem Projekt &quot;{0}&quot; speichern, bevor Sie FlowBlox verlassen? ähnelt.
        /// </summary>
        internal static string AppWindow_SaveBeforeExit_Message {
            get {
                return ResourceManager.GetString("AppWindow_SaveBeforeExit_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt speichern? ähnelt.
        /// </summary>
        internal static string AppWindow_SaveBeforeExit_Title {
            get {
                return ResourceManager.GetString("AppWindow_SaveBeforeExit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Speichervorgang konnte nicht erfolgreich abgeschlossen werden. Bitte überprüfen Sie die Logfiles um mehr Informationen zu erhalten. ähnelt.
        /// </summary>
        internal static string AppWindow_SaveFailed_Message {
            get {
                return ResourceManager.GetString("AppWindow_SaveFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern fehlgeschlagen ähnelt.
        /// </summary>
        internal static string AppWindow_SaveFailed_Title {
            get {
                return ResourceManager.GetString("AppWindow_SaveFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (!) Stellen Sie sicher, dass Ihre Änderungen gespeichert wurden. ähnelt.
        /// </summary>
        internal static string AppWindow_SaveReminder_Message {
            get {
                return ResourceManager.GetString("AppWindow_SaveReminder_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FlowBlox ähnelt.
        /// </summary>
        internal static string AppWindow_Text {
            get {
                return ResourceManager.GetString("AppWindow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Projekt konnte nicht vollständig entladen werden. Die folgenden Assemblies oder Erweiterungen sind weiterhin im Speicher und verhindern ein sauberes Entladen:
        ///
        ///{0}
        ///
        ///Die Anwendung wird jetzt neu gestartet, um eine saubere Umgebung wiederherzustellen. ähnelt.
        /// </summary>
        internal static string AppWindow_UnloadProjectFailed_Message {
            get {
                return ResourceManager.GetString("AppWindow_UnloadProjectFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt konnte nicht entladen werden ähnelt.
        /// </summary>
        internal static string AppWindow_UnloadProjectFailed_Title {
            get {
                return ResourceManager.GetString("AppWindow_UnloadProjectFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erweiterungen verwalten ähnelt.
        /// </summary>
        internal static string ComponentLibraryPanel_btManageExtensions_Text {
            get {
                return ResourceManager.GetString("ComponentLibraryPanel_btManageExtensions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Komponentenbibliothek ähnelt.
        /// </summary>
        internal static string ComponentLibraryPanel_Text {
            get {
                return ResourceManager.GetString("ComponentLibraryPanel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Annehmen ähnelt.
        /// </summary>
        internal static string CreateEntryWindow_btApply_Text {
            get {
                return ResourceManager.GetString("CreateEntryWindow_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Zurück ähnelt.
        /// </summary>
        internal static string CreateEntryWindow_btCancel_Text {
            get {
                return ResourceManager.GetString("CreateEntryWindow_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eintrag erstellen ähnelt.
        /// </summary>
        internal static string CreateEntryWindow_Text {
            get {
                return ResourceManager.GetString("CreateEntryWindow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Annehmen ähnelt.
        /// </summary>
        internal static string EditValueWindow_btApply_Text {
            get {
                return ResourceManager.GetString("EditValueWindow_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Zurück ähnelt.
        /// </summary>
        internal static string EditValueWindow_btCancel_Text {
            get {
                return ResourceManager.GetString("EditValueWindow_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reguläre Ausdrücke automatisch maskieren ähnelt.
        /// </summary>
        internal static string EditValueWindow_cbMaskRegex_Text {
            get {
                return ResourceManager.GetString("EditValueWindow_cbMaskRegex_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hier können Sie einen Wert erstellen oder bearbeiten. ähnelt.
        /// </summary>
        internal static string EditValueWindow_lbDescription_Text {
            get {
                return ResourceManager.GetString("EditValueWindow_lbDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter: ähnelt.
        /// </summary>
        internal static string EditValueWindow_lbParameter_Text {
            get {
                return ResourceManager.GetString("EditValueWindow_lbParameter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wert: ähnelt.
        /// </summary>
        internal static string EditValueWindow_lbValue_Text {
            get {
                return ResourceManager.GetString("EditValueWindow_lbValue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wert {0} ähnelt.
        /// </summary>
        internal static string EditValueWindow_Text {
            get {
                return ResourceManager.GetString("EditValueWindow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Weiter ähnelt.
        /// </summary>
        internal static string EditValueWindow_TextContinue {
            get {
                return ResourceManager.GetString("EditValueWindow_TextContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wert erstellen ähnelt.
        /// </summary>
        internal static string EditValueWindow_TextCreateValue {
            get {
                return ResourceManager.GetString("EditValueWindow_TextCreateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wert bearbeiten ähnelt.
        /// </summary>
        internal static string EditValueWindow_TextEditValue {
            get {
                return ResourceManager.GetString("EditValueWindow_TextEditValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie einen gültigen Wert ein. ähnelt.
        /// </summary>
        internal static string EditValueWindow_TextInvalid_Message {
            get {
                return ResourceManager.GetString("EditValueWindow_TextInvalid_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungültige Eingabe ähnelt.
        /// </summary>
        internal static string EditValueWindow_TextInvalid_Title {
            get {
                return ResourceManager.GetString("EditValueWindow_TextInvalid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Zurück ähnelt.
        /// </summary>
        internal static string FieldSelectionWindiw_btCancel_Text {
            get {
                return ResourceManager.GetString("FieldSelectionWindiw_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Annehmen ähnelt.
        /// </summary>
        internal static string FieldSelectionWindow_btApply_Text {
            get {
                return ResourceManager.GetString("FieldSelectionWindow_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Zurück ähnelt.
        /// </summary>
        internal static string FieldSelectionWindow_btCancel_Text {
            get {
                return ResourceManager.GetString("FieldSelectionWindow_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erforderlich ähnelt.
        /// </summary>
        internal static string FieldSelectionWindow_cbRequired_Text {
            get {
                return ResourceManager.GetString("FieldSelectionWindow_cbRequired_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wählen Sie ein vorhandenes Feldelement aus. ähnelt.
        /// </summary>
        internal static string FieldSelectionWindow_lbDescription_Text {
            get {
                return ResourceManager.GetString("FieldSelectionWindow_lbDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Felddefinitionen ähnelt.
        /// </summary>
        internal static string FieldSelectionWindow_lbFieldDefinitions_Text {
            get {
                return ResourceManager.GetString("FieldSelectionWindow_lbFieldDefinitions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feldauswahl: Wählen Sie ein Feldelement aus ähnelt.
        /// </summary>
        internal static string FieldSelectionWindow_Text {
            get {
                return ResourceManager.GetString("FieldSelectionWindow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feldwert(e) &amp;kopieren ähnelt.
        /// </summary>
        internal static string FieldView_itmCopy_Text {
            get {
                return ResourceManager.GetString("FieldView_itmCopy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Im Standardeditor ö&amp;ffnen ähnelt.
        /// </summary>
        internal static string FieldView_itmOpenFieldValue_Text {
            get {
                return ResourceManager.GetString("FieldView_itmOpenFieldValue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Aktualisieren ähnelt.
        /// </summary>
        internal static string FieldView_itmRefresh_Text {
            get {
                return ResourceManager.GetString("FieldView_itmRefresh_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feldansicht ähnelt.
        /// </summary>
        internal static string FieldView_Text {
            get {
                return ResourceManager.GetString("FieldView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Annehmen ähnelt.
        /// </summary>
        internal static string FlowBlockMainView_btApply_Text {
            get {
                return ResourceManager.GetString("FlowBlockMainView_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Zurück ähnelt.
        /// </summary>
        internal static string FlowBlockMainView_btCancel_Text {
            get {
                return ResourceManager.GetString("FlowBlockMainView_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgabefeld: {0} (Vollqualifizierter Feldname: {1}) ähnelt.
        /// </summary>
        internal static string FlowBlockUIElementRenderer_Field_Tooltip {
            get {
                return ResourceManager.GetString("FlowBlockUIElementRenderer_Field_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieses Feld ist für die Ausführung erforderlich: {0} ähnelt.
        /// </summary>
        internal static string FlowBlockUIElementRenderer_RequiredFields_Tooltip {
            get {
                return ResourceManager.GetString("FlowBlockUIElementRenderer_RequiredFields_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Annehmen ähnelt.
        /// </summary>
        internal static string GridView_btApply_Text {
            get {
                return ResourceManager.GetString("GridView_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Zurück ähnelt.
        /// </summary>
        internal static string GridView_btCancel_Text {
            get {
                return ResourceManager.GetString("GridView_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legen Sie hier die Größe Ihres Rasters fest. Die Werte werden sofort auf das aktuelle Projekt-Raster übernommen. ähnelt.
        /// </summary>
        internal static string GridView_lbDescription_Text {
            get {
                return ResourceManager.GetString("GridView_lbDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Höhe ähnelt.
        /// </summary>
        internal static string GridView_lbHeight_Text {
            get {
                return ResourceManager.GetString("GridView_lbHeight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Breite ähnelt.
        /// </summary>
        internal static string GridView_lbWidth_Text {
            get {
                return ResourceManager.GetString("GridView_lbWidth_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Raster bearbeiten ähnelt.
        /// </summary>
        internal static string GridView_Text {
            get {
                return ResourceManager.GetString("GridView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Annehmen ähnelt.
        /// </summary>
        internal static string InsertTextOrField_btApply_Text {
            get {
                return ResourceManager.GetString("InsertTextOrField_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Zurück ähnelt.
        /// </summary>
        internal static string InsertTextOrField_btCancel_Text {
            get {
                return ResourceManager.GetString("InsertTextOrField_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feld &amp;auswählen ähnelt.
        /// </summary>
        internal static string InsertTextOrField_btSelectField_Text {
            get {
                return ResourceManager.GetString("InsertTextOrField_btSelectField_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einen Feldwert übergeben: ähnelt.
        /// </summary>
        internal static string InsertTextOrField_lbInsertField_Text {
            get {
                return ResourceManager.GetString("InsertTextOrField_lbInsertField_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einen eigenen Wert eingeben: ähnelt.
        /// </summary>
        internal static string InsertTextOrField_lbInsertText_Text {
            get {
                return ResourceManager.GetString("InsertTextOrField_lbInsertText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgewählter Parameter ähnelt.
        /// </summary>
        internal static string InsertTextOrField_lbParameterHeader_Text {
            get {
                return ResourceManager.GetString("InsertTextOrField_lbParameterHeader_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wählen... ähnelt.
        /// </summary>
        internal static string InsertTextOrField_NoFieldSelected_Text {
            get {
                return ResourceManager.GetString("InsertTextOrField_NoFieldSelected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wert eingeben oder Feld auswählen ähnelt.
        /// </summary>
        internal static string InsertTextOrField_Text {
            get {
                return ResourceManager.GetString("InsertTextOrField_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Hinzufügen ähnelt.
        /// </summary>
        internal static string OptionsWindow_btAdd_Text {
            get {
                return ResourceManager.GetString("OptionsWindow_btAdd_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Entfernen ähnelt.
        /// </summary>
        internal static string OptionsWindow_btDelete_Text {
            get {
                return ResourceManager.GetString("OptionsWindow_btDelete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Standardoptionen laden ähnelt.
        /// </summary>
        internal static string OptionsWindow_btRevert_Text {
            get {
                return ResourceManager.GetString("OptionsWindow_btRevert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Speichern ähnelt.
        /// </summary>
        internal static string OptionView_btApply_Text {
            get {
                return ResourceManager.GetString("OptionView_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung: ähnelt.
        /// </summary>
        internal static string OptionView_labelDescription_Text {
            get {
                return ResourceManager.GetString("OptionView_labelDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        internal static string OptionView_labelName_Text {
            get {
                return ResourceManager.GetString("OptionView_labelName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Option bearbeiten ähnelt.
        /// </summary>
        internal static string OptionView_labelTitleHeader_Text {
            get {
                return ResourceManager.GetString("OptionView_labelTitleHeader_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Typ: ähnelt.
        /// </summary>
        internal static string OptionView_labelType_Text {
            get {
                return ResourceManager.GetString("OptionView_labelType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wert: ähnelt.
        /// </summary>
        internal static string OptionView_labelValue_Text {
            get {
                return ResourceManager.GetString("OptionView_labelValue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinzufügen ähnelt.
        /// </summary>
        internal static string OptionWindow_btAdd_Text {
            get {
                return ResourceManager.GetString("OptionWindow_btAdd_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Annehmen ähnelt.
        /// </summary>
        internal static string OptionWindow_btApply_Text {
            get {
                return ResourceManager.GetString("OptionWindow_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Zurück ähnelt.
        /// </summary>
        internal static string OptionWindow_btCancel_Text {
            get {
                return ResourceManager.GetString("OptionWindow_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entfernen ähnelt.
        /// </summary>
        internal static string OptionWindow_btDelete_Text {
            get {
                return ResourceManager.GetString("OptionWindow_btDelete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optionen zurücksetzen ähnelt.
        /// </summary>
        internal static string OptionWindow_btRevert_Text {
            get {
                return ResourceManager.GetString("OptionWindow_btRevert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Durch diesen Befehl werden bestehende Optionswerte wieder auf ihren Standard zurückgesetzt. Wollen Sie wirklich die Standardoptionen wiederherstellen? ähnelt.
        /// </summary>
        internal static string OptionWindow_RevertOptions_Message {
            get {
                return ResourceManager.GetString("OptionWindow_RevertOptions_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optionen zurücksetzen ähnelt.
        /// </summary>
        internal static string OptionWindow_RevertOptions_Title {
            get {
                return ResourceManager.GetString("OptionWindow_RevertOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optionen ähnelt.
        /// </summary>
        internal static string OptionWindow_Text {
            get {
                return ResourceManager.GetString("OptionWindow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Probleme ähnelt.
        /// </summary>
        internal static string ProblemsView_Text {
            get {
                return ResourceManager.GetString("ProblemsView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbinden ähnelt.
        /// </summary>
        internal static string ProjectPanel_btConnectionMode_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_btConnectionMode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Ausführen ähnelt.
        /// </summary>
        internal static string ProjectPanel_btExecute_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_btExecute_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Rastergröße anpassen ähnelt.
        /// </summary>
        internal static string ProjectPanel_btGridSettings_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_btGridSettings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Pausieren ähnelt.
        /// </summary>
        internal static string ProjectPanel_btPause_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_btPause_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auswählen ähnelt.
        /// </summary>
        internal static string ProjectPanel_btSelectionMode_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_btSelectionMode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Stoppen ähnelt.
        /// </summary>
        internal static string ProjectPanel_btStopExecution_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_btStopExecution_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Haltepunkt &amp;entfernen ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmBreakPoint_Remove_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmBreakPoint_Remove_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Haltepunkt &amp;setzen ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmBreakPoint_Set_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmBreakPoint_Set_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Haltepunkt &amp;setzten ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmBreakPoint_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmBreakPoint_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index &amp;festlegen ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmDefineIndex_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmDefineIndex_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbindung e&amp;ntfernen ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmDeleteConnection_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmDeleteConnection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flow-Block e&amp;ntfernen ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmDeleteElement_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmDeleteElement_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigenschaften &amp;bearbeiten ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmEditElement_Edit_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmEditElement_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigenschaften &amp;bearbeiten ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmEditElement_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmEditElement_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigenschaften &amp;betrachten ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmEditElement_View_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmEditElement_View_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Index verwalten ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmIndex_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmIndex_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eingangsdatensätze einsehen ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmInsightInput_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmInsightInput_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgangsdatensätze einsehen ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmInsightOutput_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmInsightOutput_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unterdrückte &amp;Meldungen verwalten ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmManageWarningSuppressions_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmManageWarningSuppressions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A&amp;ktualisieren ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmRefresh_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmRefresh_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index &amp;entfernen ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmRemoveIndex_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmRemoveIndex_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Annehmen ähnelt.
        /// </summary>
        internal static string ProjectView_btApply_Text {
            get {
                return ResourceManager.GetString("ProjectView_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Zurück ähnelt.
        /// </summary>
        internal static string ProjectView_btCancel_Text {
            get {
                return ResourceManager.GetString("ProjectView_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt erstellen ähnelt.
        /// </summary>
        internal static string ProjectView_CreateProject_Text {
            get {
                return ResourceManager.GetString("ProjectView_CreateProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ProjectView_EditProject_Text {
            get {
                return ResourceManager.GetString("ProjectView_EditProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ersteller ähnelt.
        /// </summary>
        internal static string ProjectView_lbCreator_Text {
            get {
                return ResourceManager.GetString("ProjectView_lbCreator_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hier können Sie ein neues Projekt erstellen oder die Projekteigenschaften bearbeiten. ähnelt.
        /// </summary>
        internal static string ProjectView_lbDescription_Text {
            get {
                return ResourceManager.GetString("ProjectView_lbDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinweis beim Öffnen ähnelt.
        /// </summary>
        internal static string ProjectView_lbNoteOnOpening_Text {
            get {
                return ResourceManager.GetString("ProjectView_lbNoteOnOpening_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projektbeschreibung ähnelt.
        /// </summary>
        internal static string ProjectView_lbProjectDescription_Text {
            get {
                return ResourceManager.GetString("ProjectView_lbProjectDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projektbezeichnung ähnelt.
        /// </summary>
        internal static string ProjectView_lbProjectName_Text {
            get {
                return ResourceManager.GetString("ProjectView_lbProjectName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Ermitteln der verfügbaren Aktionen für die Komponente ist ein Fehler aufgetreten. Weitere Details finden Sie in den Anwendungsprotokollen. ähnelt.
        /// </summary>
        internal static string PropertyViewListViewFactory_ComponentActionsLoadingFailure_Message {
            get {
                return ResourceManager.GetString("PropertyViewListViewFactory_ComponentActionsLoadingFailure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Laden der Aktionen ähnelt.
        /// </summary>
        internal static string PropertyViewListViewFactory_ComponentActionsLoadingFailure_Title {
            get {
                return ResourceManager.GetString("PropertyViewListViewFactory_ComponentActionsLoadingFailure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wählen Sie ein Objekt aus. ähnelt.
        /// </summary>
        internal static string PropertyViewListViewFactory_SelectionDialog_Message {
            get {
                return ResourceManager.GetString("PropertyViewListViewFactory_SelectionDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auswählen ähnelt.
        /// </summary>
        internal static string PropertyViewListViewFactory_SelectionDialog_Title {
            get {
                return ResourceManager.GetString("PropertyViewListViewFactory_SelectionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Annehmen ähnelt.
        /// </summary>
        internal static string PropertyWindow_btApply_Text {
            get {
                return ResourceManager.GetString("PropertyWindow_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Zurück ähnelt.
        /// </summary>
        internal static string PropertyWindow_btCancel_Text {
            get {
                return ResourceManager.GetString("PropertyWindow_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Annehmen ähnelt.
        /// </summary>
        internal static string RenameWindow_btApply_Text {
            get {
                return ResourceManager.GetString("RenameWindow_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Zurück ähnelt.
        /// </summary>
        internal static string RenameWindow_btCancel_Text {
            get {
                return ResourceManager.GetString("RenameWindow_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --- Aktueller Wert: ähnelt.
        /// </summary>
        internal static string RenameWindow_lbCurrentValue_Text {
            get {
                return ResourceManager.GetString("RenameWindow_lbCurrentValue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --- Neuer Wert: ähnelt.
        /// </summary>
        internal static string RenameWindow_lbNewValue_Text {
            get {
                return ResourceManager.GetString("RenameWindow_lbNewValue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eintrag umbenennen ähnelt.
        /// </summary>
        internal static string RenameWindow_Text {
            get {
                return ResourceManager.GetString("RenameWindow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgabe lee&amp;ren ähnelt.
        /// </summary>
        internal static string RuntimeView_btClear_Text {
            get {
                return ResourceManager.GetString("RuntimeView_btClear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Fortsetzen ähnelt.
        /// </summary>
        internal static string RuntimeView_btContinue_Text {
            get {
                return ResourceManager.GetString("RuntimeView_btContinue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Logfile öffnen ähnelt.
        /// </summary>
        internal static string RuntimeView_btOpenLogfile_Text {
            get {
                return ResourceManager.GetString("RuntimeView_btOpenLogfile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Pause ähnelt.
        /// </summary>
        internal static string RuntimeView_btPause_Text {
            get {
                return ResourceManager.GetString("RuntimeView_btPause_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Aktualisieren ähnelt.
        /// </summary>
        internal static string RuntimeView_btRefresh_Text {
            get {
                return ResourceManager.GetString("RuntimeView_btRefresh_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausführung &amp;stoppen ähnelt.
        /// </summary>
        internal static string RuntimeView_btStopExecution_Text {
            get {
                return ResourceManager.GetString("RuntimeView_btStopExecution_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schrittweise &amp;ausführen ähnelt.
        /// </summary>
        internal static string RuntimeView_cbStepwiseExecution_Text {
            get {
                return ResourceManager.GetString("RuntimeView_cbStepwiseExecution_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bei &amp;Fehler anhalten ähnelt.
        /// </summary>
        internal static string RuntimeView_cbStopOnError_Text {
            get {
                return ResourceManager.GetString("RuntimeView_cbStopOnError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bei &amp;Warnung anhalten ähnelt.
        /// </summary>
        internal static string RuntimeView_cbStopOnWarning_Text {
            get {
                return ResourceManager.GetString("RuntimeView_cbStopOnWarning_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Exportverzeichnis ähnelt.
        /// </summary>
        internal static string RuntimeView_itmExportDir_Text {
            get {
                return ResourceManager.GetString("RuntimeView_itmExportDir_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laufzeit ähnelt.
        /// </summary>
        internal static string RuntimeView_Text {
            get {
                return ResourceManager.GetString("RuntimeView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Versuch die Ansicht zu erzeugen ist es zu einem unerwarteten Fehler gekommen. Bitte überprüfen Sie die Logfiles, um mehr Informationen zu erhalten. ähnelt.
        /// </summary>
        internal static string WindowsFormWPFHelper_ShowDialog_Failure_Message {
            get {
                return ResourceManager.GetString("WindowsFormWPFHelper_ShowDialog_Failure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzeigen des Dialogs fehlgeschlagen ähnelt.
        /// </summary>
        internal static string WindowsFormWPFHelper_ShowDialog_Failure_Title {
            get {
                return ResourceManager.GetString("WindowsFormWPFHelper_ShowDialog_Failure_Title", resourceCulture);
            }
        }
    }
}
