//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowBlox {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FlowBloxMainUITexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlowBloxMainUITexts() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowBlox.FlowBloxMainUITexts", typeof(FlowBloxMainUITexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Product information ähnelt.
        /// </summary>
        internal static string About_groupBoxProductInformation_Text {
            get {
                return ResourceManager.GetString("About_groupBoxProductInformation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About FlowBlox ähnelt.
        /// </summary>
        internal static string About_Text {
            get {
                return ResourceManager.GetString("About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to close the project &quot;{0}&quot;? ähnelt.
        /// </summary>
        internal static string AppWindow_CloseProjectConfirm_Message {
            get {
                return ResourceManager.GetString("AppWindow_CloseProjectConfirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close Project? ähnelt.
        /// </summary>
        internal static string AppWindow_CloseProjectConfirm_Title {
            get {
                return ResourceManager.GetString("AppWindow_CloseProjectConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please report this error at https://www.flowblox.net/. ähnelt.
        /// </summary>
        internal static string AppWindow_ErrorReport_Message {
            get {
                return ResourceManager.GetString("AppWindow_ErrorReport_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FlowBlox Error Report ähnelt.
        /// </summary>
        internal static string AppWindow_ErrorReport_Title {
            get {
                return ResourceManager.GetString("AppWindow_ErrorReport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open GitHub repository ähnelt.
        /// </summary>
        internal static string AppWindow_GitHub_Text {
            get {
                return ResourceManager.GetString("AppWindow_GitHub_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not export the current FlowBlox.Grid as a bitmap (*.bmp). Please check the log files for more information. ähnelt.
        /// </summary>
        internal static string AppWindow_GridExportFailed_Message {
            get {
                return ResourceManager.GetString("AppWindow_GridExportFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FlowBlox.Grid: Export Problem ähnelt.
        /// </summary>
        internal static string AppWindow_GridExportFailed_Title {
            get {
                return ResourceManager.GetString("AppWindow_GridExportFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;About FlowBlox ähnelt.
        /// </summary>
        internal static string AppWindow_itmAbout_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmAbout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto-align flow ähnelt.
        /// </summary>
        internal static string AppWindow_itmAutoAdjustFlowLayout_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmAutoAdjustFlowLayout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for updates... ähnelt.
        /// </summary>
        internal static string AppWindow_itmCheckForNewVersion_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmCheckForNewVersion_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Close project ähnelt.
        /// </summary>
        internal static string AppWindow_itmCloseProject_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmCloseProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Copy ähnelt.
        /// </summary>
        internal static string AppWindow_itmCopy_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmCopy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Create new project ähnelt.
        /// </summary>
        internal static string AppWindow_itmCreateProject_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmCreateProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Delete element ähnelt.
        /// </summary>
        internal static string AppWindow_itmDeleteElement_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmDeleteElement_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Dockable panels ähnelt.
        /// </summary>
        internal static string AppWindow_itmDockablePanels_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmDockablePanels_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Edit properties ähnelt.
        /// </summary>
        internal static string AppWindow_itmEditProject_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmEditProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage extensions ähnelt.
        /// </summary>
        internal static string AppWindow_itmFbExtensions_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmFbExtensions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View projects (Project-Space) ähnelt.
        /// </summary>
        internal static string AppWindow_itmFbProjects_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmFbProjects_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visit us on GitHub ähnelt.
        /// </summary>
        internal static string AppWindow_itmGitHub_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmGitHub_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;License ähnelt.
        /// </summary>
        internal static string AppWindow_itmLicense_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmLicense_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Sign in ähnelt.
        /// </summary>
        internal static string AppWindow_itmLogin_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmLogin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign &amp;out ähnelt.
        /// </summary>
        internal static string AppWindow_itmLogout_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmLogout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage input files ähnelt.
        /// </summary>
        internal static string AppWindow_itmManageInputFiles_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmManageInputFiles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitoring ähnelt.
        /// </summary>
        internal static string AppWindow_itmMonitor_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmMonitor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show application log file(s) ähnelt.
        /// </summary>
        internal static string AppWindow_itmOpenApplicationLogDirectory_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmOpenApplicationLogDirectory_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open from Project-Space ähnelt.
        /// </summary>
        internal static string AppWindow_itmOpenFromProjectSpace_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmOpenFromProjectSpace_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open input directory ähnelt.
        /// </summary>
        internal static string AppWindow_itmOpenInputDir_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmOpenInputDir_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Open output folder ähnelt.
        /// </summary>
        internal static string AppWindow_itmOpenOutputDir_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmOpenOutputDir_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Open project ähnelt.
        /// </summary>
        internal static string AppWindow_itmOpenProject_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmOpenProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open project &amp;folder ähnelt.
        /// </summary>
        internal static string AppWindow_itmOpenProjectDir_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmOpenProjectDir_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open project input directory ähnelt.
        /// </summary>
        internal static string AppWindow_itmOpenProjectInputDir_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmOpenProjectInputDir_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open project output directory ähnelt.
        /// </summary>
        internal static string AppWindow_itmOpenProjectOutputDir_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmOpenProjectOutputDir_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show runtime log file(s) ähnelt.
        /// </summary>
        internal static string AppWindow_itmOpenRuntimeLogDirectory_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmOpenRuntimeLogDirectory_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Options... ähnelt.
        /// </summary>
        internal static string AppWindow_itmOptions_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmOptions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Paste ähnelt.
        /// </summary>
        internal static string AppWindow_itmPaste_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmPaste_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Exit ähnelt.
        /// </summary>
        internal static string AppWindow_itmQuitApplication_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmQuitApplication_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recent projects ähnelt.
        /// </summary>
        internal static string AppWindow_itmRecentProjects_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmRecentProjects_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Redo ähnelt.
        /// </summary>
        internal static string AppWindow_itmRedo_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmRedo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Register ähnelt.
        /// </summary>
        internal static string AppWindow_itmRegister_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmRegister_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Report a problem ähnelt.
        /// </summary>
        internal static string AppWindow_itmReportProblem_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmReportProblem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Reset dockable dialogues ähnelt.
        /// </summary>
        internal static string AppWindow_itmResetDockablePanels_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmResetDockablePanels_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save project &amp;as ähnelt.
        /// </summary>
        internal static string AppWindow_itmSaveAs_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmSaveAs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Save project ähnelt.
        /// </summary>
        internal static string AppWindow_itmSaveProject_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmSaveProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save to Project Space ähnelt.
        /// </summary>
        internal static string AppWindow_itmSaveToProjectSpace_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmSaveToProjectSpace_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Toolbox ähnelt.
        /// </summary>
        internal static string AppWindow_itmToolbox_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmToolbox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Undo ähnelt.
        /// </summary>
        internal static string AppWindow_itmUndo_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmUndo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Custom fields ähnelt.
        /// </summary>
        internal static string AppWindow_itmUserFields_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmUserFields_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visit online ähnelt.
        /// </summary>
        internal static string AppWindow_itmVisitOnline_Text {
            get {
                return ResourceManager.GetString("AppWindow_itmVisitOnline_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account ähnelt.
        /// </summary>
        internal static string AppWindow_mnItmAccount_Text {
            get {
                return ResourceManager.GetString("AppWindow_mnItmAccount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Directories ähnelt.
        /// </summary>
        internal static string AppWindow_mnItmDirectories_Text {
            get {
                return ResourceManager.GetString("AppWindow_mnItmDirectories_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Edit ähnelt.
        /// </summary>
        internal static string AppWindow_mnItmEdit_Text {
            get {
                return ResourceManager.GetString("AppWindow_mnItmEdit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Help ähnelt.
        /// </summary>
        internal static string AppWindow_mnItmHelp_Text {
            get {
                return ResourceManager.GetString("AppWindow_mnItmHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Tools ähnelt.
        /// </summary>
        internal static string AppWindow_mnItmMisc_Text {
            get {
                return ResourceManager.GetString("AppWindow_mnItmMisc_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Project ähnelt.
        /// </summary>
        internal static string AppWindow_mnItmProject_Text {
            get {
                return ResourceManager.GetString("AppWindow_mnItmProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;View ähnelt.
        /// </summary>
        internal static string AppWindow_mnItmWindows_Text {
            get {
                return ResourceManager.GetString("AppWindow_mnItmWindows_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to close the project &quot;{0}&quot; and create a new project? ähnelt.
        /// </summary>
        internal static string AppWindow_NewProjectConfirm_Message {
            get {
                return ResourceManager.GetString("AppWindow_NewProjectConfirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create New Project? ähnelt.
        /// </summary>
        internal static string AppWindow_NewProjectConfirm_Title {
            get {
                return ResourceManager.GetString("AppWindow_NewProjectConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download update ähnelt.
        /// </summary>
        internal static string AppWindow_Notification_UpdateAvailable_Action_Text {
            get {
                return ResourceManager.GetString("AppWindow_Notification_UpdateAvailable_Action_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A new FlowBlox update is available. ähnelt.
        /// </summary>
        internal static string AppWindow_Notification_UpdateAvailable_Message {
            get {
                return ResourceManager.GetString("AppWindow_Notification_UpdateAvailable_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The update installer has been downloaded. ähnelt.
        /// </summary>
        internal static string AppWindow_Notification_UpdateDownloaded_Message {
            get {
                return ResourceManager.GetString("AppWindow_Notification_UpdateDownloaded_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install update ähnelt.
        /// </summary>
        internal static string AppWindow_Notification_UpdateInstallDownloaded_Action_Text {
            get {
                return ResourceManager.GetString("AppWindow_Notification_UpdateInstallDownloaded_Action_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to close the project &quot;{0}&quot; and load another project? ähnelt.
        /// </summary>
        internal static string AppWindow_OpenProjectConfirm_Message {
            get {
                return ResourceManager.GetString("AppWindow_OpenProjectConfirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load New Project? ähnelt.
        /// </summary>
        internal static string AppWindow_OpenProjectConfirm_Title {
            get {
                return ResourceManager.GetString("AppWindow_OpenProjectConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The page could not be opened: {0} ähnelt.
        /// </summary>
        internal static string AppWindow_OpenUrlFailed_Message {
            get {
                return ResourceManager.GetString("AppWindow_OpenUrlFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could Not Open Page ähnelt.
        /// </summary>
        internal static string AppWindow_OpenUrlFailed_Title {
            get {
                return ResourceManager.GetString("AppWindow_OpenUrlFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The project could not be fully loaded. When you close this window, an error report will be generated automatically. Please also check the log files for more details about the causes of the problem. ähnelt.
        /// </summary>
        internal static string AppWindow_ProjectLoadFailed_Message {
            get {
                return ResourceManager.GetString("AppWindow_ProjectLoadFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Not Fully Loaded ähnelt.
        /// </summary>
        internal static string AppWindow_ProjectLoadFailed_Title {
            get {
                return ResourceManager.GetString("AppWindow_ProjectLoadFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notice on Open ähnelt.
        /// </summary>
        internal static string AppWindow_ProjectNotice_Title {
            get {
                return ResourceManager.GetString("AppWindow_ProjectNotice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please stop the current execution before closing FlowBlox. ähnelt.
        /// </summary>
        internal static string AppWindow_RuntimeActiveClose_Message {
            get {
                return ResourceManager.GetString("AppWindow_RuntimeActiveClose_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Caution: Runtime Active ähnelt.
        /// </summary>
        internal static string AppWindow_RuntimeActiveClose_Title {
            get {
                return ResourceManager.GetString("AppWindow_RuntimeActiveClose_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to save changes to the project &quot;{0}&quot; before leaving FlowBlox? ähnelt.
        /// </summary>
        internal static string AppWindow_SaveBeforeExit_Message {
            get {
                return ResourceManager.GetString("AppWindow_SaveBeforeExit_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Project? ähnelt.
        /// </summary>
        internal static string AppWindow_SaveBeforeExit_Title {
            get {
                return ResourceManager.GetString("AppWindow_SaveBeforeExit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The save operation could not be completed successfully. Please check the log files for more information. ähnelt.
        /// </summary>
        internal static string AppWindow_SaveFailed_Message {
            get {
                return ResourceManager.GetString("AppWindow_SaveFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Failed ähnelt.
        /// </summary>
        internal static string AppWindow_SaveFailed_Title {
            get {
                return ResourceManager.GetString("AppWindow_SaveFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (!) Make sure your changes have been saved. ähnelt.
        /// </summary>
        internal static string AppWindow_SaveReminder_Message {
            get {
                return ResourceManager.GetString("AppWindow_SaveReminder_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FlowBlox ähnelt.
        /// </summary>
        internal static string AppWindow_Text {
            get {
                return ResourceManager.GetString("AppWindow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The project could not be fully unloaded. The following assemblies or extensions are still in memory and prevent a clean unload:
        ///
        ///{0}
        ///
        ///The application will now restart to restore a clean environment. ähnelt.
        /// </summary>
        internal static string AppWindow_UnloadProjectFailed_Message {
            get {
                return ResourceManager.GetString("AppWindow_UnloadProjectFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could Not Unload Project ähnelt.
        /// </summary>
        internal static string AppWindow_UnloadProjectFailed_Title {
            get {
                return ResourceManager.GetString("AppWindow_UnloadProjectFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while checking for updates. ähnelt.
        /// </summary>
        internal static string AppWindow_UpdateCheck_Error_Message {
            get {
                return ResourceManager.GetString("AppWindow_UpdateCheck_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unexpected error occurred while checking for updates. ähnelt.
        /// </summary>
        internal static string AppWindow_UpdateCheck_Exception_Message {
            get {
                return ResourceManager.GetString("AppWindow_UpdateCheck_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version check could not be performed because no installer update source is configured. ähnelt.
        /// </summary>
        internal static string AppWindow_UpdateCheck_NotPackaged_Message {
            get {
                return ResourceManager.GetString("AppWindow_UpdateCheck_NotPackaged_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No update available. ähnelt.
        /// </summary>
        internal static string AppWindow_UpdateCheck_NoUpdates_Message {
            get {
                return ResourceManager.GetString("AppWindow_UpdateCheck_NoUpdates_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The update source is unknown. Opening the website for manual checking. ähnelt.
        /// </summary>
        internal static string AppWindow_UpdateCheck_UnknownSource_Message {
            get {
                return ResourceManager.GetString("AppWindow_UpdateCheck_UnknownSource_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The update could not be installed. Please try again later or download the current version from the website. ähnelt.
        /// </summary>
        internal static string AppWindow_UpdateInstall_Failed_Message {
            get {
                return ResourceManager.GetString("AppWindow_UpdateInstall_Failed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open FlowBlox website ähnelt.
        /// </summary>
        internal static string AppWindow_VisitOnline_Text {
            get {
                return ResourceManager.GetString("AppWindow_VisitOnline_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage extensions ähnelt.
        /// </summary>
        internal static string ComponentLibraryPanel_btManageExtensions_Text {
            get {
                return ResourceManager.GetString("ComponentLibraryPanel_btManageExtensions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Component library ähnelt.
        /// </summary>
        internal static string ComponentLibraryPanel_Text {
            get {
                return ResourceManager.GetString("ComponentLibraryPanel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Apply ähnelt.
        /// </summary>
        internal static string CreateEntryWindow_btApply_Text {
            get {
                return ResourceManager.GetString("CreateEntryWindow_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Back ähnelt.
        /// </summary>
        internal static string CreateEntryWindow_btCancel_Text {
            get {
                return ResourceManager.GetString("CreateEntryWindow_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Entry ähnelt.
        /// </summary>
        internal static string CreateEntryWindow_Text {
            get {
                return ResourceManager.GetString("CreateEntryWindow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Apply ähnelt.
        /// </summary>
        internal static string EditValueWindow_btApply_Text {
            get {
                return ResourceManager.GetString("EditValueWindow_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Back ähnelt.
        /// </summary>
        internal static string EditValueWindow_btCancel_Text {
            get {
                return ResourceManager.GetString("EditValueWindow_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatically escape regular expressions ähnelt.
        /// </summary>
        internal static string EditValueWindow_cbMaskRegex_Text {
            get {
                return ResourceManager.GetString("EditValueWindow_cbMaskRegex_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Here you can create or edit a value. ähnelt.
        /// </summary>
        internal static string EditValueWindow_lbDescription_Text {
            get {
                return ResourceManager.GetString("EditValueWindow_lbDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter: ähnelt.
        /// </summary>
        internal static string EditValueWindow_lbParameter_Text {
            get {
                return ResourceManager.GetString("EditValueWindow_lbParameter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value: ähnelt.
        /// </summary>
        internal static string EditValueWindow_lbValue_Text {
            get {
                return ResourceManager.GetString("EditValueWindow_lbValue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value {0} ähnelt.
        /// </summary>
        internal static string EditValueWindow_Text {
            get {
                return ResourceManager.GetString("EditValueWindow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Next ähnelt.
        /// </summary>
        internal static string EditValueWindow_TextContinue {
            get {
                return ResourceManager.GetString("EditValueWindow_TextContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create value ähnelt.
        /// </summary>
        internal static string EditValueWindow_TextCreateValue {
            get {
                return ResourceManager.GetString("EditValueWindow_TextCreateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit value ähnelt.
        /// </summary>
        internal static string EditValueWindow_TextEditValue {
            get {
                return ResourceManager.GetString("EditValueWindow_TextEditValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a valid value. ähnelt.
        /// </summary>
        internal static string EditValueWindow_TextInvalid_Message {
            get {
                return ResourceManager.GetString("EditValueWindow_TextInvalid_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Input ähnelt.
        /// </summary>
        internal static string EditValueWindow_TextInvalid_Title {
            get {
                return ResourceManager.GetString("EditValueWindow_TextInvalid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Back ähnelt.
        /// </summary>
        internal static string FieldSelectionWindiw_btCancel_Text {
            get {
                return ResourceManager.GetString("FieldSelectionWindiw_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Apply ähnelt.
        /// </summary>
        internal static string FieldSelectionWindow_btApply_Text {
            get {
                return ResourceManager.GetString("FieldSelectionWindow_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Back ähnelt.
        /// </summary>
        internal static string FieldSelectionWindow_btCancel_Text {
            get {
                return ResourceManager.GetString("FieldSelectionWindow_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Required ähnelt.
        /// </summary>
        internal static string FieldSelectionWindow_cbRequired_Text {
            get {
                return ResourceManager.GetString("FieldSelectionWindow_cbRequired_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select an existing field element. ähnelt.
        /// </summary>
        internal static string FieldSelectionWindow_lbDescription_Text {
            get {
                return ResourceManager.GetString("FieldSelectionWindow_lbDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Field definitions ähnelt.
        /// </summary>
        internal static string FieldSelectionWindow_lbFieldDefinitions_Text {
            get {
                return ResourceManager.GetString("FieldSelectionWindow_lbFieldDefinitions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Field Selection: Choose a field element ähnelt.
        /// </summary>
        internal static string FieldSelectionWindow_Text {
            get {
                return ResourceManager.GetString("FieldSelectionWindow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show flow block ähnelt.
        /// </summary>
        internal static string FieldView_checkBoxShowFlowBlock_Text {
            get {
                return ResourceManager.GetString("FieldView_checkBoxShowFlowBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Copy field value(s) ähnelt.
        /// </summary>
        internal static string FieldView_itmCopy_Text {
            get {
                return ResourceManager.GetString("FieldView_itmCopy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open in &amp;default editor ähnelt.
        /// </summary>
        internal static string FieldView_itmOpenFieldValue_Text {
            get {
                return ResourceManager.GetString("FieldView_itmOpenFieldValue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Refresh ähnelt.
        /// </summary>
        internal static string FieldView_itmRefresh_Text {
            get {
                return ResourceManager.GetString("FieldView_itmRefresh_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Field view ähnelt.
        /// </summary>
        internal static string FieldView_Text {
            get {
                return ResourceManager.GetString("FieldView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Apply ähnelt.
        /// </summary>
        internal static string FlowBlockMainView_btApply_Text {
            get {
                return ResourceManager.GetString("FlowBlockMainView_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Back ähnelt.
        /// </summary>
        internal static string FlowBlockMainView_btCancel_Text {
            get {
                return ResourceManager.GetString("FlowBlockMainView_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Execution index: {0} ähnelt.
        /// </summary>
        internal static string FlowBlockUIElement_ExecutionIndex_Text {
            get {
                return ResourceManager.GetString("FlowBlockUIElement_ExecutionIndex_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Output field: {0} (Fully qualified field name: {1}) ähnelt.
        /// </summary>
        internal static string FlowBlockUIElementRenderer_Field_Tooltip {
            get {
                return ResourceManager.GetString("FlowBlockUIElementRenderer_Field_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This field is required for execution: {0} ähnelt.
        /// </summary>
        internal static string FlowBlockUIElementRenderer_RequiredFields_Tooltip {
            get {
                return ResourceManager.GetString("FlowBlockUIElementRenderer_RequiredFields_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Apply ähnelt.
        /// </summary>
        internal static string GridView_btApply_Text {
            get {
                return ResourceManager.GetString("GridView_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Back ähnelt.
        /// </summary>
        internal static string GridView_btCancel_Text {
            get {
                return ResourceManager.GetString("GridView_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set the size of your grid here. The values are applied immediately to the current project grid. ähnelt.
        /// </summary>
        internal static string GridView_lbDescription_Text {
            get {
                return ResourceManager.GetString("GridView_lbDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Height ähnelt.
        /// </summary>
        internal static string GridView_lbHeight_Text {
            get {
                return ResourceManager.GetString("GridView_lbHeight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Width ähnelt.
        /// </summary>
        internal static string GridView_lbWidth_Text {
            get {
                return ResourceManager.GetString("GridView_lbWidth_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit grid ähnelt.
        /// </summary>
        internal static string GridView_Text {
            get {
                return ResourceManager.GetString("GridView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Apply ähnelt.
        /// </summary>
        internal static string InsertTextOrField_btApply_Text {
            get {
                return ResourceManager.GetString("InsertTextOrField_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Back ähnelt.
        /// </summary>
        internal static string InsertTextOrField_btCancel_Text {
            get {
                return ResourceManager.GetString("InsertTextOrField_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Select field ähnelt.
        /// </summary>
        internal static string InsertTextOrField_btSelectField_Text {
            get {
                return ResourceManager.GetString("InsertTextOrField_btSelectField_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pass a field value: ähnelt.
        /// </summary>
        internal static string InsertTextOrField_lbInsertField_Text {
            get {
                return ResourceManager.GetString("InsertTextOrField_lbInsertField_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a custom value: ähnelt.
        /// </summary>
        internal static string InsertTextOrField_lbInsertText_Text {
            get {
                return ResourceManager.GetString("InsertTextOrField_lbInsertText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selected parameter ähnelt.
        /// </summary>
        internal static string InsertTextOrField_lbParameterHeader_Text {
            get {
                return ResourceManager.GetString("InsertTextOrField_lbParameterHeader_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please choose... ähnelt.
        /// </summary>
        internal static string InsertTextOrField_NoFieldSelected_Text {
            get {
                return ResourceManager.GetString("InsertTextOrField_NoFieldSelected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter value or select field ähnelt.
        /// </summary>
        internal static string InsertTextOrField_Text {
            get {
                return ResourceManager.GetString("InsertTextOrField_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Add ähnelt.
        /// </summary>
        internal static string OptionsWindow_btAdd_Text {
            get {
                return ResourceManager.GetString("OptionsWindow_btAdd_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Remove ähnelt.
        /// </summary>
        internal static string OptionsWindow_btDelete_Text {
            get {
                return ResourceManager.GetString("OptionsWindow_btDelete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load &amp;default options ähnelt.
        /// </summary>
        internal static string OptionsWindow_btRevert_Text {
            get {
                return ResourceManager.GetString("OptionsWindow_btRevert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Save ähnelt.
        /// </summary>
        internal static string OptionView_btApply_Text {
            get {
                return ResourceManager.GetString("OptionView_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description: ähnelt.
        /// </summary>
        internal static string OptionView_labelDescription_Text {
            get {
                return ResourceManager.GetString("OptionView_labelDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available as placeholder ähnelt.
        /// </summary>
        internal static string OptionView_labelIsPlaceholderEnabled_Text {
            get {
                return ResourceManager.GetString("OptionView_labelIsPlaceholderEnabled_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        internal static string OptionView_labelName_Text {
            get {
                return ResourceManager.GetString("OptionView_labelName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit option ähnelt.
        /// </summary>
        internal static string OptionView_labelTitleHeader_Text {
            get {
                return ResourceManager.GetString("OptionView_labelTitleHeader_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type: ähnelt.
        /// </summary>
        internal static string OptionView_labelType_Text {
            get {
                return ResourceManager.GetString("OptionView_labelType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value: ähnelt.
        /// </summary>
        internal static string OptionView_labelValue_Text {
            get {
                return ResourceManager.GetString("OptionView_labelValue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string OptionView_No {
            get {
                return ResourceManager.GetString("OptionView_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string OptionView_Yes {
            get {
                return ResourceManager.GetString("OptionView_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        internal static string OptionWindow_btAdd_Text {
            get {
                return ResourceManager.GetString("OptionWindow_btAdd_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Apply ähnelt.
        /// </summary>
        internal static string OptionWindow_btApply_Text {
            get {
                return ResourceManager.GetString("OptionWindow_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Back ähnelt.
        /// </summary>
        internal static string OptionWindow_btCancel_Text {
            get {
                return ResourceManager.GetString("OptionWindow_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        internal static string OptionWindow_btDelete_Text {
            get {
                return ResourceManager.GetString("OptionWindow_btDelete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset options ähnelt.
        /// </summary>
        internal static string OptionWindow_btRevert_Text {
            get {
                return ResourceManager.GetString("OptionWindow_btRevert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This command resets existing option values to their defaults. Do you really want to restore the default options? ähnelt.
        /// </summary>
        internal static string OptionWindow_RevertOptions_Message {
            get {
                return ResourceManager.GetString("OptionWindow_RevertOptions_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset Options ähnelt.
        /// </summary>
        internal static string OptionWindow_RevertOptions_Title {
            get {
                return ResourceManager.GetString("OptionWindow_RevertOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        internal static string OptionWindow_Text {
            get {
                return ResourceManager.GetString("OptionWindow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problems ähnelt.
        /// </summary>
        internal static string ProblemsView_Text {
            get {
                return ResourceManager.GetString("ProblemsView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No start flow block was found. Automatic alignment cannot be performed. ähnelt.
        /// </summary>
        internal static string ProjectPanel_AutoAdjust_NoStart_Message {
            get {
                return ResourceManager.GetString("ProjectPanel_AutoAdjust_NoStart_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No automatic alignment ähnelt.
        /// </summary>
        internal static string ProjectPanel_AutoAdjust_NoStart_Title {
            get {
                return ResourceManager.GetString("ProjectPanel_AutoAdjust_NoStart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto align ähnelt.
        /// </summary>
        internal static string ProjectPanel_btAutoAdjustFlowLayout_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_btAutoAdjustFlowLayout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect ähnelt.
        /// </summary>
        internal static string ProjectPanel_btConnectionMode_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_btConnectionMode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Run ähnelt.
        /// </summary>
        internal static string ProjectPanel_btExecute_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_btExecute_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string ProjectPanel_btGridSettings_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_btGridSettings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Pause ähnelt.
        /// </summary>
        internal static string ProjectPanel_btPause_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_btPause_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select ähnelt.
        /// </summary>
        internal static string ProjectPanel_btSelectionMode_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_btSelectionMode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Stop ähnelt.
        /// </summary>
        internal static string ProjectPanel_btStopExecution_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_btStopExecution_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} (Copy) ähnelt.
        /// </summary>
        internal static string ProjectPanel_Copy_NameFormat {
            get {
                return ResourceManager.GetString("ProjectPanel_Copy_NameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove &amp;breakpoint ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmBreakPoint_Remove_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmBreakPoint_Remove_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Set breakpoint ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmBreakPoint_Set_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmBreakPoint_Set_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Breakpoint ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmBreakPoint_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmBreakPoint_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Set execution index ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmDefineIndex_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmDefineIndex_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Delete connection ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmDeleteConnection_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmDeleteConnection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Delete flow block ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmDeleteElement_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmDeleteElement_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Edit properties ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmEditElement_Edit_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmEditElement_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Edit properties ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmEditElement_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmEditElement_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;View properties ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmEditElement_View_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmEditElement_View_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage execution &amp;index ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmIndex_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmIndex_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inspect input records ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmInsightInput_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmInsightInput_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inspect output records ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmInsightOutput_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmInsightOutput_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage &amp;notifications ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmManageNotifications_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmManageNotifications_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Refresh ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmRefresh_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmRefresh_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Remove execution index ähnelt.
        /// </summary>
        internal static string ProjectPanel_itmRemoveIndex_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_itmRemoveIndex_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invoke ähnelt.
        /// </summary>
        internal static string ProjectPanel_labelInvoke_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_labelInvoke_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Iteration Context ähnelt.
        /// </summary>
        internal static string ProjectPanel_labelIterationContext_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_labelIterationContext_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recursive Call ähnelt.
        /// </summary>
        internal static string ProjectPanel_labelRecursiveCall_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_labelRecursiveCall_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The runtime was aborted due to an unexpected error.{1}Runtime exception:{1}{0} ähnelt.
        /// </summary>
        internal static string ProjectPanel_RuntimeAborted_Message {
            get {
                return ResourceManager.GetString("ProjectPanel_RuntimeAborted_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Runtime aborted ähnelt.
        /// </summary>
        internal static string ProjectPanel_RuntimeAborted_Title {
            get {
                return ResourceManager.GetString("ProjectPanel_RuntimeAborted_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The execution could not be started: {0} ähnelt.
        /// </summary>
        internal static string ProjectPanel_RuntimeStartFailed_Message {
            get {
                return ResourceManager.GetString("ProjectPanel_RuntimeStartFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Runtime execution failed ähnelt.
        /// </summary>
        internal static string ProjectPanel_RuntimeStartFailed_Title {
            get {
                return ResourceManager.GetString("ProjectPanel_RuntimeStartFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are grid elements that are never executed. Affected elements: {0} ähnelt.
        /// </summary>
        internal static string ProjectPanel_Warning_NotExecutedElements_Text {
            get {
                return ResourceManager.GetString("ProjectPanel_Warning_NotExecutedElements_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Apply ähnelt.
        /// </summary>
        internal static string ProjectView_btApply_Text {
            get {
                return ResourceManager.GetString("ProjectView_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Back ähnelt.
        /// </summary>
        internal static string ProjectView_btCancel_Text {
            get {
                return ResourceManager.GetString("ProjectView_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create project ähnelt.
        /// </summary>
        internal static string ProjectView_CreateProject_Text {
            get {
                return ResourceManager.GetString("ProjectView_CreateProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit project ähnelt.
        /// </summary>
        internal static string ProjectView_EditProject_Text {
            get {
                return ResourceManager.GetString("ProjectView_EditProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creator ähnelt.
        /// </summary>
        internal static string ProjectView_lbCreator_Text {
            get {
                return ResourceManager.GetString("ProjectView_lbCreator_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Here you can create a new project or edit the project properties. ähnelt.
        /// </summary>
        internal static string ProjectView_lbDescription_Text {
            get {
                return ResourceManager.GetString("ProjectView_lbDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project input directory ähnelt.
        /// </summary>
        internal static string ProjectView_lbInputDir_Text {
            get {
                return ResourceManager.GetString("ProjectView_lbInputDir_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notice on open ähnelt.
        /// </summary>
        internal static string ProjectView_lbNoteOnOpening_Text {
            get {
                return ResourceManager.GetString("ProjectView_lbNoteOnOpening_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project output directory ähnelt.
        /// </summary>
        internal static string ProjectView_lbOutputDir_Text {
            get {
                return ResourceManager.GetString("ProjectView_lbOutputDir_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project description ähnelt.
        /// </summary>
        internal static string ProjectView_lbProjectDescription_Text {
            get {
                return ResourceManager.GetString("ProjectView_lbProjectDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project name ähnelt.
        /// </summary>
        internal static string ProjectView_lbProjectName_Text {
            get {
                return ResourceManager.GetString("ProjectView_lbProjectName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred while determining the available actions for the component. See the application logs for details. ähnelt.
        /// </summary>
        internal static string PropertyViewListViewFactory_ComponentActionsLoadingFailure_Message {
            get {
                return ResourceManager.GetString("PropertyViewListViewFactory_ComponentActionsLoadingFailure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to Load Actions ähnelt.
        /// </summary>
        internal static string PropertyViewListViewFactory_ComponentActionsLoadingFailure_Title {
            get {
                return ResourceManager.GetString("PropertyViewListViewFactory_ComponentActionsLoadingFailure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select an object. ähnelt.
        /// </summary>
        internal static string PropertyViewListViewFactory_SelectionDialog_Message {
            get {
                return ResourceManager.GetString("PropertyViewListViewFactory_SelectionDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select ähnelt.
        /// </summary>
        internal static string PropertyViewListViewFactory_SelectionDialog_Title {
            get {
                return ResourceManager.GetString("PropertyViewListViewFactory_SelectionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Apply ähnelt.
        /// </summary>
        internal static string PropertyWindow_btApply_Text {
            get {
                return ResourceManager.GetString("PropertyWindow_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Back ähnelt.
        /// </summary>
        internal static string PropertyWindow_btCancel_Text {
            get {
                return ResourceManager.GetString("PropertyWindow_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Apply ähnelt.
        /// </summary>
        internal static string RenameWindow_btApply_Text {
            get {
                return ResourceManager.GetString("RenameWindow_btApply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Back ähnelt.
        /// </summary>
        internal static string RenameWindow_btCancel_Text {
            get {
                return ResourceManager.GetString("RenameWindow_btCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --- Current value: ähnelt.
        /// </summary>
        internal static string RenameWindow_lbCurrentValue_Text {
            get {
                return ResourceManager.GetString("RenameWindow_lbCurrentValue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --- New value: ähnelt.
        /// </summary>
        internal static string RenameWindow_lbNewValue_Text {
            get {
                return ResourceManager.GetString("RenameWindow_lbNewValue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename Entry ähnelt.
        /// </summary>
        internal static string RenameWindow_Text {
            get {
                return ResourceManager.GetString("RenameWindow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clea&amp;r output ähnelt.
        /// </summary>
        internal static string RuntimeView_btClear_Text {
            get {
                return ResourceManager.GetString("RuntimeView_btClear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Continue ähnelt.
        /// </summary>
        internal static string RuntimeView_btContinue_Text {
            get {
                return ResourceManager.GetString("RuntimeView_btContinue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open &amp;log file ähnelt.
        /// </summary>
        internal static string RuntimeView_btOpenLogfile_Text {
            get {
                return ResourceManager.GetString("RuntimeView_btOpenLogfile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Pause ähnelt.
        /// </summary>
        internal static string RuntimeView_btPause_Text {
            get {
                return ResourceManager.GetString("RuntimeView_btPause_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Refresh ähnelt.
        /// </summary>
        internal static string RuntimeView_btRefresh_Text {
            get {
                return ResourceManager.GetString("RuntimeView_btRefresh_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Stop execution ähnelt.
        /// </summary>
        internal static string RuntimeView_btStopExecution_Text {
            get {
                return ResourceManager.GetString("RuntimeView_btStopExecution_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Run step by step ähnelt.
        /// </summary>
        internal static string RuntimeView_cbStepwiseExecution_Text {
            get {
                return ResourceManager.GetString("RuntimeView_cbStepwiseExecution_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop on &amp;error ähnelt.
        /// </summary>
        internal static string RuntimeView_cbStopOnError_Text {
            get {
                return ResourceManager.GetString("RuntimeView_cbStopOnError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop on &amp;warning ähnelt.
        /// </summary>
        internal static string RuntimeView_cbStopOnWarning_Text {
            get {
                return ResourceManager.GetString("RuntimeView_cbStopOnWarning_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Export folder ähnelt.
        /// </summary>
        internal static string RuntimeView_itmExportDir_Text {
            get {
                return ResourceManager.GetString("RuntimeView_itmExportDir_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Runtime ähnelt.
        /// </summary>
        internal static string RuntimeView_Text {
            get {
                return ResourceManager.GetString("RuntimeView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build, Test, and Run Flows (based on .NET) ähnelt.
        /// </summary>
        internal static string SplashWindow_LabelMessage_Text {
            get {
                return ResourceManager.GetString("SplashWindow_LabelMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unexpected error occurred while trying to create the view. Please check the log files for more information. ähnelt.
        /// </summary>
        internal static string WindowsFormWPFHelper_ShowDialog_Failure_Message {
            get {
                return ResourceManager.GetString("WindowsFormWPFHelper_ShowDialog_Failure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to Show Dialog ähnelt.
        /// </summary>
        internal static string WindowsFormWPFHelper_ShowDialog_Failure_Title {
            get {
                return ResourceManager.GetString("WindowsFormWPFHelper_ShowDialog_Failure_Title", resourceCulture);
            }
        }
    }
}
